### PR TITLE
Annotation feature gate for Console

### PR DESCRIPTION
**Pull request by umangachapagain**
An annotation containing an array of unique identifiers for
console features is added to enable/disable them as needed.

### CODE REVIEW

**Comment by bipuladh** [comment]
@umangachapagain looks like we might have some issues in UI implementing these values.

**Comment by cloudbehl** [comment]
@bipuladh can you describe what is the issues you are seeing? https://github.com/openshift/console/pull/5079

**Comment by bipuladh** [comment]
@cloudbehl I have described the issue at https://github.com/openshift/console/pull/5079/files#r411286609

**Pull request merged**
