### PR TITLE
Adding 'Ready' phase for External StorageCluster Mode

### PR DESCRIPTION
**Pull request by aruniiird**
This PR adds `Ready` state for independent mode type storage cluster.

According to the discussion with Travis and others, once IM storage cluster can be considered as `Ready` once connected.

Fixes: https://github.com/openshift/ocs-operator/issues/478

Signed-off-by: Arun Kumar Mohan <arun.iiird@gmail.com>

### CODE REVIEW

**Comment by aruniiird** [comment]
@umangachapagain , @jarrpa , @vbnrh , please review...

**Comment by aruniiird** [comment]
@jarrpa , I have removed the `Connected` phase and included only the `Ready` phase (once connected)... Please take a look...

image

**Comment by anmolsachan** [comment]
> I don't see the point of this PR. Either `PhaseConnected` needs to be removed or some other differentiator between `PhaseConnected` and `PhaseReady` needs to be introduced.

The thought behind having Connected and Ready phase was that of accomodating any post connection operation that the cluster needs to do. Since there is none right now, it makes sense to have just Ready. 
Also introducing Ready is required to keep the experience consistent across both converged and independent mode, since UI recognizes the Ready phase and gives it a green icon.

**Comment by aruniiird** [comment]
@jarrpa , made the changes...

**Comment by aruniiird** [comment]
@jarrpa , rebased with latest master...

**Comment by jarrpa** [comment]
Functional tests failing due to an unknown networking error, bypassing.

/override ci/prow/ocs-operator-e2e-aws

**Pull request merged**
