### PR TITLE
Bug 1977329: [release-4.8] Allow DBStorageClass to be set from Storage Cluster CR for Noobaa

### PR DESCRIPTION
**Pull request by ezio-auditore**
Backport of #1298

Signed-off-by: Kaustav Majumder kmajumder@redhat.com

### CODE REVIEW

**Review by umangachapagain — CHANGES_REQUESTED** [review]
Changes needs to be done in master branch before we can backport it into 4.8.
This adds a new api spec, so I'm not sure if this can be taken directly into 4.8.

@agarwal-mudit @obnoxxx WDYT?

**Comment by agarwal-mudit** [comment]
/hold
Correct, release-4.8 is now frozen. Also, the BZ is not approved for 4.8 and we are already in RC

**Comment by ezio-auditore** [comment]
This has to be rebased until 4.8 is released and merged with 4.8.1. Also i think  in 4.9 this spec will no more be required since MCG spec  to be decoupled from storage cluster spec. This is something we require in Openshift Dedicated ODF addon to run MCG without consuming pv from ocs-ceph-rbd for nooba-db pod.

**Review by umangachapagain — CHANGES_REQUESTED** [review]
Change looks good. But commit needs to be divided into 2.
We prefer Go changes in one commit and generated changes (CRD and CSV) in a separate commit.

**Comment by ezio-auditore** [comment]
@umangachapagain  Moved generated changes in new commit.

**Review by umangachapagain — APPROVED** [review]

**Comment by jarrpa** [comment]
Closing in favor of #1302

**Comment by jarrpa** [comment]
...opening this up again because #1302 is invalid. :joy: This PR's branch should be (force) updated with the relevant fixes.

/hold

**Review by jarrpa — APPROVED** [review]
/lgtm
/hold cancel

**Pull request merged**
