### PR TITLE
Bug 1915737: [release-4.7] storagecluster: Fix noobaa uninstall logs

### PR DESCRIPTION
**Pull request by iamniting**
Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

Fix https://bugzilla.redhat.com/show_bug.cgi?id=1915737

### CODE REVIEW

**Comment by crombus** [comment]
I think they are similar PR's https://github.com/openshift/ocs-operator/pull/1057

**Comment by iamniting** [comment]
> I think they are similar PR's #1057

This one is backport

**Comment by agarwal-mudit** [comment]
/retitle Bug 1915737: [release-4.7] storagecluster: Fix noobaa uninstall logs

**Comment by agarwal-mudit** [comment]
@iamniting Backport PR should be created after the master PR is merged by cherry-picking the changes. 
Unless I am missing something, this PR should be closed.

**Comment by iamniting** [comment]
@agarwal-mudit I have cherry-picked these changes myself manually as I was aware that there will be merge conflict and can not be done in an automated way.

I did it before the other PR is merged to speed up the process.

**Review by obnoxxx — APPROVED** [review]
In general we should wait until master PR is merged. But as long as we merge after the master PR merges and make sure to update the backport PR if the master PR needs update, we should be OK.

/lgtm

**Pull request merged**
