### PR TITLE
added  toleration to csi pods

### PR DESCRIPTION
**Pull request by umangachapagain**
- added Env Vars for rook-ceph operator to allow csi
to tolerate required taints

Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>

### CODE REVIEW

**Comment by nehaberry** [comment]
@umangachapagain if this PR is already merged, why are CSI provisioner pods still unable to come up on OCS tainted nodes  in a 3 worker node setup? Am I missing some particular setting 

```
  READY   STATUS    RESTARTS   AGE    IP            NODE                                         NOMINATED NODE   READINESS GATES
csi-cephfsplugin-provisioner-587c9ccf8d-66mrl   0/4     Pending   0          4m8s   <none>        <none>                                       <none>           <none>
csi-cephfsplugin-provisioner-587c9ccf8d-fflvg   0/4     Pending   0          4m8s   <none>        <none>                                       <none>           <none>
csi-rbdplugin-provisioner-766d79f78-f7gdd       0/5     Pending   0          4m8s   <none>        <none>                                       <none>           <none>
csi-rbdplugin-provisioner-766d79f78-slknh       0/5     Pending   0          4m8s   <none>        <none>                                       <none>           <none>
```
```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  59s (x7 over 5m18s)  default-scheduler  0/6 nodes are available: 6 node(s) had taints that the pod didn't tolerate.
```

```
$ oc get ClusterServiceVersion -n openshift-storage -o yaml|grep TOLERATIONS -A5 -B1
                    value: "true"
                  - name: CSI_PROVISIONER_TOLERATIONS
                    value: |2-

                      - key: node.ocs.openshift.io/storage
                        operator: Equal
                        value: "true"
                        effect: NoSchedule
                  - name: CSI_PLUGIN_TOLERATIONS
                    value: |2-

                      - key: node.ocs.openshift.io/storage
                        operator: Equal
                        value: "true"

```

Versions used:

```
ocs-operator-967957d84-vj52h
==================
    Image:         quay.io/ocs-dev/ocs-operator:latest
    Image ID:      quay.io/ocs-dev/ocs-operator@sha256:195564aa330f2723918f94d41fabb04971e11b3c58d6b76916f6beda2645cbe6

rook-ceph-operator-8446d776fd-j92b4
==================
    Image:         rook/ceph:v1.1.1
    Image ID:      docker.io/rook/ceph@sha256:cdfae616420533878ed7527df622644b6149e705e3fa280011d231b4948e06fc

$ oc get csv 
NAME                            DISPLAY                                VERSION   REPLACES   PHASE
local-storage-operator.v4.2.0   Local Storage                          4.2.0                Succeeded
ocs-operator.v0.0.1             Openshift Container Storage Operator   0.0.1                Succeeded

```

**Comment by umangachapagain** [comment]
> ```
> $ oc get ClusterServiceVersion -n openshift-storage -o yaml|grep TOLERATIONS -A5 -B1
>                     value: "true"
>                   - name: CSI_PROVISIONER_TOLERATIONS
>                     value: |2-
> 
>                       - key: node.ocs.openshift.io/storage
>                         operator: Equal
>                         value: "true"
>                         effect: NoSchedule
>                   - name: CSI_PLUGIN_TOLERATIONS
>                     value: |2-
> 
>                       - key: node.ocs.openshift.io/storage
>                         operator: Equal
>                         value: "true"
> ```
> 
These Env Vars are passed to Rook Operator deployment. (That's all this PR does)
CSV is showing proper values, which means either rook operator is not receiving it or not using it properly. In either case, that would be a rook issue.

Can you check
`oc get pods rook-operator-XXXXXX -oyaml -nopenshift-storage` 
if it has these csi ENV Vars set?

Also, rook-operator logs to see whats happening with these values.

**Comment by nehaberry** [comment]
[rook-ceph-operator-8446d776fd-j92b4.log](https://github.com/openshift/ocs-operator/files/3706764/rook-ceph-operator-8446d776fd-j92b4.log)
[rook-ceph-operator-8446d776fd-j92b4.yaml.zip](https://github.com/openshift/ocs-operator/files/3706765/rook-ceph-operator-8446d776fd-j92b4.yaml.zip)

Attached the output. These envs are set as seen in the rook-ceph-operator pod.

    - name: CSI_PROVISIONER_TOLERATIONS
      value: |2-


Once I added a 4th un-tainted node, only then my CSI provisioner pods got scheduled:

```
$ oc get pods -o wide
NAME                                                              READY   STATUS      RESTARTS   AGE     IP             NODE                                         NOMINATED NODE   READINESS GATES
csi-cephfsplugin-provisioner-587c9ccf8d-66mrl                     4/4     Running     0          4h20m   10.130.2.6     ip-10-0-137-230.us-east-2.compute.internal   <none>           <none>
csi-cephfsplugin-provisioner-587c9ccf8d-fflvg                     4/4     Running     0          4h20m   10.130.2.5     ip-10-0-137-230.us-east-2.compute.internal   <none>           <none>
csi-cephfsplugin-xmgpr                                            3/3     Running     0          3h57m   10.0.137.230   ip-10-0-137-230.us-east-2.compute.internal   <none>           <none>
csi-rbdplugin-hm76s                                               3/3     Running     0          3h57m   10.0.137.230   ip-10-0-137-230.us-east-2.compute.internal   <none>           <none>
csi-rbdplugin-provisioner-766d79f78-f7gdd                         5/5     Running     0          4h20m   10.130.2.7     ip-10-0-137-230.us-east-2.compute.internal   <none>           <none>
csi-rbdplugin-provisioner-766d79f78-slknh                         5/5     Running     0          4h20m   10.130.2.8     ip-10-0-137-230.us-east-2.compute.internal   <none>           <none>
```

```
$ for i in $(oc get nodes|grep -v master|grep -v NAME|awk '{print$1}') ; do echo $i; echo =;  oc get node $i  -o yaml|grep taint -B 2 -A4;  done

ip-10-0-133-114.us-east-2.compute.internal
=
spec:
  providerID: aws:///us-east-2a/i-04783e6689e2b6509
  taints:
  - effect: NoSchedule
    key: node.ocs.openshift.io/storage
    value: "true"
status:


ip-10-0-137-230.us-east-2.compute.internal  <--new node added
[rook-ceph-operator-8446d776fd-j92b4.log](https://github.com/openshift/ocs-operator/files/3706762/rook-ceph-operator-8446d776fd-j92b4.log)

=

ip-10-0-155-108.us-east-2.compute.internal
=
spec:
  providerID: aws:///us-east-2b/i-06dfdcfc7fce7d9b5
  taints:
  - effect: NoSchedule
    key: node.ocs.openshift.io/storage
    value: "true"
status:
ip-10-0-170-6.us-east-2.compute.internal
=
spec:
  providerID: aws:///us-east-2c/i-0f9b11a23a9fbf5ef
  taints:
  - effect: NoSchedule
    key: node.ocs.openshift.io/storage
    value: "true"
status:
```

**Comment by Madhu-1** [comment]
https://github.com/openshift/ocs-operator/pull/197 fixes this issue by using rook v1.1.2 which supports toleration

**Pull request merged**
