### PR TITLE
Inject labels to all the monitoring resources created by OCS

### PR DESCRIPTION
**Pull request by umangachapagain**
`labels` field is used to inject labels into all the monitoring
resources created by OCS operator and it's sub-components.

`mergo.Merge` will merge all the labels and overwrite non empty
values. Precedence is given to source labels.

### CODE REVIEW

**Review by jarrpa — CHANGES_REQUESTED** [review]
I like this! I remember looking at mergo some time ago for... something or another, so this is good.

Regarding the commits, I don't like having the API changes be separate from the functional implementation. In part its how I do reviews on GitHub, but conceptually it makes each one feel incomplete without the other. Could I ask you to merge them? This would involve rewriting the commit messages a bit, sorry.

**Comment by umangachapagain** [comment]
> I like this! I remember looking at mergo some time ago for... something or another, so this is good.
> 
> Regarding the commits, I don't like having the API changes be separate from the functional implementation. In part its how I do reviews on GitHub, but conceptually it makes each one feel incomplete without the other. Could I ask you to merge them? This would involve rewriting the commit messages a bit, sorry.

Done.

**Comment by jarrpa** [comment]
Looks like there are valid CI errors. Please verify.

**Comment by umangachapagain** [comment]
> Looks like there are valid CI errors. Please verify.
>
Fixed.

**Comment by jarrpa** [comment]
e2e tests failing, and I can't find an ocs-must-gather in the artifacts... I swear we fixed that already. :( I'll trigger the tests again, but can you see if you can replicate the issue on your own cluster?

**Review by jarrpa — APPROVED** [review]
/lgtm

**Pull request merged**
