### PR TITLE
Annotating the internal CRDs

### PR DESCRIPTION
**Pull request by aruniiird**
Backend change for adding 'operators.operatorframework.io/internal-objects' annotation,
which holds an array of CRD names which are internal to the operator. This will be later
used by the UI code for hiding the internal tiles/cards.

Signed-off-by: Arun Kumar Mohan <arun.iiird@gmail.com>

### CODE REVIEW

**Comment by umangachapagain** [comment]
/hold

There is no UI support as of now to validate this fix. Let's wait till we have that.

**Comment by aruniiird** [comment]
Bipul has put a PR in the console front, which works with this PR as expected... Taken a screen shot,

Bipuls PR: https://github.com/openshift/console/pull/3877

image

**Comment by umangachapagain** [comment]
/lgtm

Can you check why the test is failing?

**Pull request merged**
