### PR TITLE
Migration to new project structure

### PR DESCRIPTION
**Pull request by umangachapagain**
**Checklist:**

- [x] Initialize new project structure
- [x] Migrate existing code to new project structure
- [x] Generate code and manifests according to new structure
- [x] Update tests
- [x] Update make targets
- [x] Build ocs-operator binary and image
- [x] Generate unified bundle (CRDs, unified CSV and RBACs)
- [x] Generate bundle image
- [x] Generate Index image
- [x] Fix CI

### CODE REVIEW

**Review by obnoxxx — CHANGES_REQUESTED** [review]
Thanks @umangachapagain !
Overall the changes look good in general.

But there is a failure in the CI (e2e tests) and I am not sure, it might be related:

```
 Waiting for ClusterServiceVersion to become ready...
Timed out waiting for csv to become ready
Dumping Namespace openshift-storage as /tmp/artifacts/ns-openshift-storage.yaml
Dumping OperatorGroup oo-46sgq as /tmp/artifacts/og-oo-46sgq.yaml
Dumping CatalogSource oo-g9hft as /tmp/artifacts/cs-oo-g9hft.yaml
Dumping Subscription oo-2l682 as /tmp/artifacts/sub-oo-2l682.yaml
  Subscription oo-2l682 status state: AtLatestKnown
ClusterServiceVersion ocs-operator.v4.7.0 was created but never became ready
Dumping ClusterServiceVersion ocs-operator.v4.7.0 as /tmp/artifacts/csv-ocs-operator.v4.7.0.yaml
  ClusterServiceVersion ocs-operator.v4.7.0 status phase: Installing
  ClusterServiceVersion ocs-operator.v4.7.0 status message: installing: waiting for deployment ocs-operator to become ready: Waiting for rollout to finish: 0 out of 1 new replicas have been updated...
  ClusterServiceVersion ocs-operator.v4.7.0 status reason: InstallWaiting
error: failed to execute wrapped command: exit status 1
2020/12/22 17:28:55 Container test in pod ocs-operator-bundle-e2e-aws-optional-operators-ci-subscribe failed, exit code 1, reason Error 
```

Furthermore, I think the file `bin/manager` has been committed accidentally.

Lastly, I would like to understand if this change would require changes in the downstream build configuration (due to changed binary paths or so ..).

**Comment by umangachapagain** [comment]
> Thanks @umangachapagain !
> Overall the changes look good in general.
> 
> But there is a failure in the CI (e2e tests) and I am not sure, it might be related:
> 
> ```
>  Waiting for ClusterServiceVersion to become ready...
> Timed out waiting for csv to become ready
> Dumping Namespace openshift-storage as /tmp/artifacts/ns-openshift-storage.yaml
> Dumping OperatorGroup oo-46sgq as /tmp/artifacts/og-oo-46sgq.yaml
> Dumping CatalogSource oo-g9hft as /tmp/artifacts/cs-oo-g9hft.yaml
> Dumping Subscription oo-2l682 as /tmp/artifacts/sub-oo-2l682.yaml
>   Subscription oo-2l682 status state: AtLatestKnown
> ClusterServiceVersion ocs-operator.v4.7.0 was created but never became ready
> Dumping ClusterServiceVersion ocs-operator.v4.7.0 as /tmp/artifacts/csv-ocs-operator.v4.7.0.yaml
>   ClusterServiceVersion ocs-operator.v4.7.0 status phase: Installing
>   ClusterServiceVersion ocs-operator.v4.7.0 status message: installing: waiting for deployment ocs-operator to become ready: Waiting for rollout to finish: 0 out of 1 new replicas have been updated...
>   ClusterServiceVersion ocs-operator.v4.7.0 status reason: InstallWaiting
> error: failed to execute wrapped command: exit status 1
> 2020/12/22 17:28:55 Container test in pod ocs-operator-bundle-e2e-aws-optional-operators-ci-subscribe failed, exit code 1, reason Error 
> ```
> 
Looking at it.
>
> Furthermore, I think the file `bin/manager` has been committed accidentally.
> 
Removed it
>
> Lastly, I would like to understand if this change would require changes in the downstream build configuration (due to changed binary paths or so ..).
>
No changes required AFAICT. I've modified most of the things to be backward compatible.

**Review by obnoxxx — APPROVED** [review]
Thanks, @umangachapagain !

/lgtm

**Pull request merged**
