### PR TITLE
Bug 1978578: [release-4.6] fixed cephTools update when spec is changed

### PR DESCRIPTION
**Pull request by agarwal-mudit**
Signed-off-by: Santosh Pillai <sapillai@redhat.com>
(cherry picked from commit e524fc1ce339429ed4263796ea4a858e81678b0b)

### CODE REVIEW

**Comment by agarwal-mudit** [comment]
/hold 
Bug is not acked

**Review by obnoxxx — COMMENTED** [review]
Why is there only a backport for 4.6 and not for 4.7 and 4.8? @agarwal-mudit

**Comment by agarwal-mudit** [comment]
> Why is there only a backport for 4.6 and not for 4.7 and 4.8? @agarwal-mudit

Its already there in 4.7 and above

**Comment by obnoxxx** [comment]
> > Why is there only a backport for 4.6 and not for 4.7 and 4.8? @agarwal-mudit
> 
> Its already there in 4.7 and above

Oh, I missed that the original PR #766 is that old... 😄

**Review by obnoxxx — APPROVED** [review]
/lgtm

**Pull request merged**
