### PR TITLE
Bug 1759288: storageclusterinit: Set Spec.DataPool for CephObjectStore

### PR DESCRIPTION
**Pull request by kshlm**
Backport of #203

### CODE REVIEW

**Comment by davidvossel** [comment]
hey, can we get a bz associated with this as well since it's a backport after dev freeze?

**Comment by kshlm** [comment]
I did. But the openshift-ci-robot [did not accept it](https://github.com/openshift/ocs-operator/pull/209#issuecomment-541670394).

**Comment by kshlm** [comment]
I'm checking with the CI team, if we can modify the requirement on the bugzilla target, or I we can remove the requirement for the bug.

We've reused the openshift CI configs where ever possible, to reduce the amount of maintenance needed by us. But we don't fully follow the openshift releases and their conventions, so the CI configs can end up not working for us.

**Comment by kshlm** [comment]
I've learnt that I need to add a custom ocs-operator configuration for the bugzilla plugin in openshift-ci, which I'll have out tomorrow.

**Pull request merged**
