### PR TITLE
Bug 1865825: [release-4.6] External resource reconciliation

### PR DESCRIPTION
**Pull request by aruniiird**
Cherry-picking the changes to `release-4.6` branch...

### CODE REVIEW

**Comment by aruniiird** [comment]
@jarrpa , @obnoxxx , please take a look...
Intention is to bring the changes from `external resource reconcile` changes (PRs: https://github.com/openshift/ocs-operator/pull/752, https://github.com/openshift/ocs-operator/pull/748) into `release-4.6` branch

**Comment by obnoxxx** [comment]
/ok-to-test

the BZ is not fully acked yet. therefore holding this:

/hold

**Comment by agarwal-mudit** [comment]
> /ok-to-test
> 
> the BZ is not fully acked yet. therefore holding this:
> 
> /hold

BZ is now approved for 4.6

**Pull request merged**
