### PR TITLE
Move api from v1alpha1 to v1

### PR DESCRIPTION
**Pull request by kshlm**

### CODE REVIEW

**Comment by kshlm** [comment]
/hold

Hold till we have confirmation that this is okay for console.

**Comment by jarrpa** [comment]
I would say we definitely don't want to do this until we release. We can lock v1alpha1 as early as we need to, but v1 shouldn't come in yet.

**Comment by travisn** [comment]
> I would say we definitely don't want to do this until we release. We can lock v1alpha1 as early as we need to, but v1 shouldn't come in yet.

If our first release is going to v1, everything before that is essentially internal testing. We should make this change now since the UI also depends on it. We don't gain anything by waiting to change the version if we don't have any releases with the alpha version. There's not a reason to deal with the complexity of changing the CRD version late in the game.

**Comment by jarrpa** [comment]
> If our first release is going to v1, everything before that is essentially internal testing. We should make this change now since the UI also depends on it. We don't gain anything by waiting to change the version if we don't have any releases with the alpha version. There's not a reason to deal with the complexity of changing the CRD version late in the game.

I am not confident the API is 100% stable at this time. There's always the risk that we will need to change the API up to dev freeze. I don't want v1 before then.

**Comment by travisn** [comment]
> I am not confident the API is 100% stable at this time. There's always the risk that we will need to change the API up to dev freeze. I don't want v1 before then.

The CRD version only matters at release time. Internally we can make all the changes we want until we release.

**Comment by jarrpa** [comment]
Sounds like a meaningless change then, in which case I'm definitely not for it. ;) As was written in another thread, we can just support both v1alpha1 and v1 at GA, if the UI ends up being stuck on v1alpha1 initially. We can backport updates to move to v1 after the fact.

**Comment by travisn** [comment]
When we release we should be using `v1`. The point I'm trying to make is that if we don't/can't do this now we will be causing more work for ourselves later to support both v1alpha1 and v1. CRD versioning issues are better to avoid if possible.

**Comment by obnoxxx** [comment]
It's normal (at least in the land where I'm originally coming from...) to have a version set before release. And the release actually locks it down. (As @travisn says.) The issue we're having here is that the UI is using the v1alpha1 release and the UI is going to freeze soon. So *if* we want to do v1, we should do it soon. and it will be frozen with the release of the operator.

@davidvossel mentioned that we could support multiple versions too.

**Comment by davidvossel** [comment]
> The issue we're having here is that the UI is using the v1alpha1 release and the UI is going to freeze soon

does this impact CI's test suite as well?

I believe it's fairly trivial to keep serving v1 and v1alpha1.  The ocs CRDs just need to keep the v1alpha1 in the versions list. that should be it.

**Example:**
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
.
.
.
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  - name: v1alpha1
    served: true
    storage: false
```

This CRD would allow us to get and retrieve objects as either "v1" or "v1alpha1".  The UI could set a CR using 'v1alpha1' and that same object could be read as 'v1' later on. 

Basically, you could make this swap to 'v1', and keep 'v1alpha1' for compatibility just by introducing that additional version field to the yaml.

**Comment by davidvossel** [comment]
all that said. If we can get away with a wholesale swap to v1, that would be the least complicated solution long term.

**Comment by davidvossel** [comment]
> I believe it's fairly trivial to keep serving v1 and v1alpha1. The ocs CRDs just need to keep the v1alpha1 in the versions list. that should be it.

One thing I didn't consider... If the UI is taking hints from examples in the CSV, we could have issues even if the backend is serving both v1 and v1alpha1.

**Comment by kshlm** [comment]
If we still can to the full swap to v1, I'd like to do it now. No point trying to maintain two versions and adding more complexity to something that we haven't even released yet.

**Comment by kshlm** [comment]
I've got a response from the console team that they are fine with this change. Is there anything else that would block this?

**Comment by obnoxxx** [comment]
Nothing that I'm aware of.

**Comment by kshlm** [comment]
Thanks @obnoxxx. I'll be rebasing this branch and do a verification once. It can be merged once done.

**Comment by kshlm** [comment]
/hold cancel

Everything is working well.

**Pull request merged**
