### PR TITLE
 must-gather: add noobaa cli to must-gather

### PR DESCRIPTION
**Pull request by crombus**
Add noobaa cli to must-gather. gathering binary from noobaa operator pod. Running the noobaa commands by executing binary.

### CODE REVIEW

**Review by umangachapagain — CHANGES_REQUESTED** [review]
Please make the commit message clearer and be consistent with Caps, Spaces etc.
Also, PR title and description can be updated to reflect the changes.

**Comment by umangachapagain** [comment]
Not a big issue but where is this cherry-picked from? Can we get rid of those commit messages since this is master?
Also remove the double signature on commit?

**Comment by crombus** [comment]
> Not a big issue but where is this cherry-picked from? Can we get rid of those commit messages since this is master?
> Also remove the double signature on commit?

I cherry-picked from github. yes. done.

**Review by jarrpa — CHANGES_REQUESTED** [review]
Makes sense to me! Please merge the first two commits.

**Review by jarrpa — APPROVED** [review]

**Pull request merged**
