### PR TITLE
Fail validation if arbiter and flexibleScaling both are enabled

### PR DESCRIPTION
**Pull request by raghavendra-talur**

### CODE REVIEW

**Comment by raghavendra-talur** [comment]
@jarrpa @umangachapagain This fixes the bug https://bugzilla.redhat.com/show_bug.cgi?id=1913357. 

cc: @iamniting

**Review by jarrpa — APPROVED** [review]
/lgtm

**Comment by jarrpa** [comment]
@vbnrh This would be another create use case to add to the admission controller.

**Comment by iamniting** [comment]
@raghavendra-talur I think we should cheery-pick this to the 4.7 branch

**Comment by agarwal-mudit** [comment]
@raghavendra-talur This has conflicts, can we manually create a backport PR for this?

**Comment by agarwal-mudit** [comment]
> @raghavendra-talur This has conflicts, can we manually create a backport PR for this?

Created https://github.com/openshift/ocs-operator/pull/1030

**Pull request merged**
