### PR TITLE
Change failure domain to zone for all cephv1.PoolSpecs

### PR DESCRIPTION
**Pull request by rohantmp**
Signed-off-by: Rohan CJ <rohantmp@redhat.com>

### CODE REVIEW

**Comment by rohantmp** [comment]
@jarrpa

**Comment by rohantmp** [comment]
@kshlm Can't seem to request a review

**Comment by obnoxxx** [comment]
@rohantmp @kshlm @jarrpa @travisn @davidvossel - I am not sure that unconditionally setting the failure domain to `zone` is actually correct: What if we want replica-3 and we don't have 3 zones? ... Wouldn't this fail? I think in AWS we have zones, that map to AZs, but some regions have less than 3 zones. What to do there? And what if OCP has only been set up with nodes in less than 3 zones? Or if the admin has not chosen/labeled/tainted nodes from 3 AZs for storage? And what if we don't have zones at all? ...

Another aspect is why the e2e CI job has succeeded. Is it using 3 zones, @davidvossel ? (I don't think so...) I can only guess that pool creation still succeeds, but that creation of objects would fail. We currently only deploy, tests that create PVs are yet to come. :-)

**Comment by obnoxxx** [comment]
I meant to comment in the issue #88 -> discussion over there please.

**Pull request merged**
