### PR TITLE
Bump to noobaa-operator 2.0.5

### PR DESCRIPTION
**Pull request by nimrod-becker**
Bump to noobaa-operator 2.0.5

No changes in api pakcage in vendor.

### CODE REVIEW

**Comment by jarrpa** [comment]
Looks like you also need to run `make update-generated`.

**Comment by jarrpa** [comment]
This needs a rebase.

**Comment by nimrod-becker** [comment]
@jarrpa rebased

**Comment by jarrpa** [comment]
@nimrod-becker You still need to run `make update-generated` and commit the changes. You can run `make ocs-openshift-ci` to verify before pushing again.

**Comment by nimrod-becker** [comment]
@jarrpa 
running
```
make update-generated OPERATOR_SDK_PLATFORM=x86_64-apple-darwin
```
Nothing changed

**Comment by jarrpa** [comment]
...ugh, found the problem:
```diff
-// Code generated by operator-sdk-v0.10.0-x86_64-apple-darwin. DO NOT EDIT.
+// Code generated by operator-sdk-v0.10.0-x86_64-linux-gnu. DO NOT EDIT.
```
For now manually edit out the change and try again. We'll look into fixing this.

**Comment by nimrod-becker** [comment]
@jarrpa right, fixed. Thanks.

**Pull request merged**
