### PR TITLE
Upgrade to Rook v1.5.1

### PR DESCRIPTION
**Pull request by umangachapagain**
Rook 1.5.1 renamed `*.crd.yaml` to `*.crds.yaml` and uses `apiextensions/v1`

### CODE REVIEW

**Comment by umangachapagain** [comment]
/hold
generated CRD is not valid. Needs rework.

**Comment by obnoxxx** [comment]
> /hold
> generated CRD is not valid. Needs rework.

@umangachapagain  are you referring to #919 ?

**Comment by umangachapagain** [comment]
> > /hold
> > generated CRD is not valid. Needs rework.
> 
> @umangachapagain are you referring to #919 ?

No. It's a different issue related to using `apiextension/v1`.

**Comment by raghavendra-talur** [comment]
@umangachapagain I think you need to update the rook version in go.mod and also commit changes after running `make deps-update`

**Comment by umangachapagain** [comment]
> @umangachapagain I think you need to update the rook version in go.mod and also commit changes after running `make deps-update`

It is done in a separate PR with all the other dependencies. It requires special handling as there are some breaking changes.

**Comment by umangachapagain** [comment]
`ci/prow/ocs-operator-bundle-e2e-aws` fails here (waiting for collector pod) but I was able to manually deploy an OCS cluster with builds from this PR. We can override this test IMO.

**Comment by jarrpa** [comment]
Let's kick off the e2e tests one more time. I'll also validate it on my end.

/test ocs-operator-bundle-e2e-aws

**Review by raghavendra-talur — APPROVED** [review]

**Comment by jarrpa** [comment]
For me it's failing on `Waiting on canary pod for node <node>`. Did something change in Rook-Ceph such that the canary Pods are no longer deployed? If so we should update the deploy-manager.

**Comment by raghavendra-talur** [comment]
> For me it's failing on `Waiting on canary pod for node <node>`. Did something change in Rook-Ceph such that the canary Pods are no longer deployed? If so we should update the deploy-manager.

I don't fully understand the change but I think https://github.com/rook/rook/pull/6489/commits/772865fa011c9ac3d34fd676e72647fcd4dc4b08 might be the reason.

It is part of the PR https://github.com/rook/rook/pull/6489/ .

**Comment by raghavendra-talur** [comment]
> > For me it's failing on `Waiting on canary pod for node <node>`. Did something change in Rook-Ceph such that the canary Pods are no longer deployed? If so we should update the deploy-manager.
> 
> I don't fully understand the change but I think [rook/rook@772865f](https://github.com/rook/rook/commit/772865fa011c9ac3d34fd676e72647fcd4dc4b08) might be the reason.
> 
> It is part of the PR [rook/rook#6489](https://github.com/rook/rook/pull/6489) .

Never mind. @jarrpa noted in a private chat that the canary pods were removed in https://github.com/rook/rook/pull/6497/files#diff-32a03f72cbf2b7d85c30ed8a2e261815b0281c9b7ccc262cf9e59556cc9fd826L116-L152

**Review by obnoxxx — APPROVED** [review]
/lgtm

**Pull request merged**
