### PR TITLE
update client-go package

### PR DESCRIPTION
**Pull request by crombus**
update client-go package allows for token
leak in logs when logLevel >= 9.

Signed-off-by: crombus <pkundra@redhat.com>

### CODE REVIEW

**Review by umangachapagain — CHANGES_REQUESTED** [review]
Few things

- Commit message sounds like we are updating package to allow leaks. Please correct it.
- Clean up `go.mod` and `go.sum` (`make deps-update`)
- Just updating client-go isn't enough. Update all K8s packages
- Ensure that no unrelated packages get updated or downgraded

**Comment by jarrpa** [comment]
@crombus Could you revisit this?

**Comment by crombus** [comment]
> @crombus Could you revisit this?

@jarrpa  updated the changes and commit msg.

**Review by umangachapagain — CHANGES_REQUESTED** [review]
This doesn't change client-go.

**Comment by crombus** [comment]
closing this PR. Issue fixed by https://github.com/openshift/ocs-operator/pull/1022.

**Pull request closed without merging**
