### PR TITLE
Remove Rook-Ceph mgr anti-affinity

### PR DESCRIPTION
**Pull request by jarrpa**
Anti-Affinity requires a topologyKey, but a good one can not be determined
  ahead of time. Rook only supports a single mgr, so the anti-affinity will
  effectively not be needed anyway.

Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Comment by jarrpa** [comment]
@travisn PTAL

**Comment by jarrpa** [comment]
@davidvossel Can you interpret the test failure? I'm not getting this when I run it locally.

**Comment by umangachapagain** [comment]
Can we just add the topologyKey: Kubernetes.io/host which is what the controller expects? This will allow HA ceph-mgr if required.

**Comment by obnoxxx** [comment]
Strange, this seems to be some golang / network issue...
```
go: finding github.com/gliderlabs/ssh v0.1.1
go: modernc.org/xc@v1.0.0: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/29fc2f846f24ce3630fdd4abfc664927c4ad22f98a3589050facafa0991faada: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly
go: finding contrib.go.opencensus.io/exporter/ocagent v0.4.11
```

**Comment by kshlm** [comment]
/close
#78 merged in place of this PR.

**Pull request closed without merging**
