### PR TITLE
updates CSV version to v4.7.0

### PR DESCRIPTION
**Pull request by umangachapagain**
Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>

### CODE REVIEW

**Review by obnoxxx — CHANGES_REQUESTED** [review]
afaict, this is missing the change in `version/versoin.go`.

As usual, I suggest to split the commit to the one introducing the change in non-generated code (`hack/common.sh` and `version/version.go`) and a second patch to commit the result of `make gen-latest-csv`.

**Comment by obnoxxx** [comment]
compare 1785b2bb719a345d615e6b5640e1bd168d2dcb9c and a914676d03b06a8eb5624f7b5b26b5f83de765b0.

**Comment by umangachapagain** [comment]
> afaict, this is missing the change in `version/versoin.go`.
> 
> As usual, I suggest to split the commit to the one introducing the change in non-generated code (`hack/common.sh` and `version/version.go`) and a second patch to commit the result of `make gen-latest-csv`.

Fixed it.

**Review by obnoxxx — APPROVED** [review]
Thanks for the update!

/lgtm

**Pull request merged**
