### PR TITLE
Added table driven tests on cephobjectstoreusers_test.go

### PR DESCRIPTION
**Pull request by priyanka19-98**
Signed off by: Priyanka Jiandani <pjiandan@redhat.com>

### CODE REVIEW

**Comment by priyanka19-98** [comment]
@jarrpa Please review

**Comment by priyanka19-98** [comment]
@jarrpa Please review

**Review by umangachapagain — CHANGES_REQUESTED** [review]
This is same as #797 .
Is this a duplicate or a mistake? Please fix it.

**Comment by priyanka19-98** [comment]
> This is same as #797 .
> Is this a duplicate or a mistake? Please fix it.

@umangachapagain  this test is for `cephobjectstoreusers` and #797 is for `cephobjectstores`

**Review by jarrpa — APPROVED** [review]

**Pull request merged**
