### PR TITLE
CR/CRD validation testing

### PR DESCRIPTION
**Pull request by jeremyary**
Hey all, while talks are still going down on how best my team and I can start throwing in on contributions, testing has been mentioned, so I wanted to start there while learning the operator. This PR adds a few tests from a shared package our team has assembled that will validate CRDs against structs as well as example CRs against CRDs. No real issues towards CR vs. CRD validation as the recent change to required sections has fixed the only failure result I hit. With struct vs. CRD, there's a lot of ground to potentially cover if your team wishes to go in a more fully declarative path. I haven't altered the CRD, but I did want to give you [a look at what that may look like](https://gist.github.com/jeremyary/34294b1a2ad1202e910139a1f433dfa4) (note this is prior to most recent CRD updates). Should you decide that you do not want to go more declarative, I can also move forward by providing the test with some section exemptions that would still allow us to validate what's included. Thanks and let me know your thoughts.

### CODE REVIEW

**Comment by mhrivnak** [comment]
Can you give us a hint as to what part of the proposed CRD is more declarative than the existing CRD and why?

**Comment by jeremyary** [comment]
Hey Michael, sure! The example gist I gave is more or less going to the extreme and fully declaring nested children objects within what's now dataPVCTemplate and admittedly there's likely a happy medium that better suits than drilling all the way down to timestamp properties deep within. That being said (and more towards the 'why') the more declarative the CRD, the more understandable the requirement for writing a CR for end-users of the operator. Similar to XSD/DTD to XML, providing good schema info will prevent users from going through time-intensive deploy/fail loops as they narrow down what does and doesn't belong in their CR and how that information has to be included/formatted. It's also worth noting that some operators are currently using an in-GUI yaml editor (as well as a command line validator) that depends on the CRD for real-time validation and helpful information (description fields). That tooling is being groomed for a wider availability within OCP. 

I'd also like to point to [one of our more mature operator examples](https://github.com/kiegroup/kie-cloud-operator/blob/master/deploy/crds/kieapp.1.1.crd.yaml) that we've worked alongside (and uses the mentioned GUI tooling) that I feel is a fair representation of a nice declarative CRD and format that we've found most easy to work with. Their CRD doesn't deep-dive every nested object, but does thoroughly document what's expected in the controller, all objects/properties that are important within the controller, and leads the user in building a successful CR.

**Comment by jeremyary** [comment]
Hey (other) Michael, once you've reached a decision internally about how much you'd like to expose via CRD (as-is, fully declarative, see if I can find a good medium perhaps), I can address it which will fix the test failures. With no changes to the CRD, the listed failures (struct vs. CRD validation) were expected.

**Comment by obnoxxx** [comment]
Thanks @jeremyary! I'll wait for @jarrpa to get back and comment on this and discuss. I am not quite sure I understand the point yet with what is declarative here and what isn't. Might be good to see it side-by-side. But the others (@jarrpa, @mhrivnak , @kshlm ...) will probably be better suited to comment. :-)

**Comment by jeremyary** [comment]
Sounds good. [Here's a diff](https://www.diffchecker.com/QI3U1CkK) to aid in discussion. I've moved version/versions up above validation, but the major differences are under nodeAffinity, podAffinity, podAntiAffinity, and tolerations - rather than just calling for 'type: object' on these, the properties of each are listed and, in turn, each property that is an object also has its properties listed (recursively).

**Comment by jarrpa** [comment]
I can't review this PR as-is. Please move all the vendor/Gopkg changes into their own commit so I can actually find what you're proposing. If possible, assuming I understand this correctly, separate the CR validation into its own commit and have the CRD changed in another commit.

**Comment by jeremyary** [comment]
breaking out into separate PR's per request

**Pull request closed without merging**
