### PR TITLE
Minor whitespace fixes

### PR DESCRIPTION
**Pull request by jarrpa**
Depends on #722.

### CODE REVIEW

**Review by obnoxxx — CHANGES_REQUESTED** [review]
This includes #722 it seems - did you intend to only have the whitespace change here?

**Comment by jarrpa** [comment]
> This includes #722 it seems - did you intend to only have the whitespace change here?

Yes, there would be merge conflicts after it merged. Which it did!

**Comment by obnoxxx** [comment]
> > This includes #722 it seems - did you intend to only have the whitespace change here?
> 
> Yes, there would be merge conflicts after it merged. Which it did!

I think we can rebase now.

**Review by obnoxxx — APPROVED** [review]
Now #722 is merged.
This will be fine since the patch from that PR is exactly the same included here.

/lgtm

**Pull request merged**
