### PR TITLE
Bump noobaa-operator version

### PR DESCRIPTION
**Pull request by nimrod-becker**
Bump noobaa-operator version to 2.0.6

### CODE REVIEW

**Comment by jarrpa** [comment]
This should not have been merged without waiting for the e2e tests to finish. We should consider making them a mandatory test for all PRs at this rate.

**Comment by guymguym** [comment]
@jarrpa can you highlight what is the failure?
Should we fix anything?
Thanks

**Comment by jarrpa** [comment]
There is a new persistent error in the e2e tests that's affecting this and other PRs, but I haven't been able to diagnose it yet. It may not be related to the NooBaa change, so no action is needed just yet. This is more a matter of principle, that something which affects the broader product, especially installation, should not be merged without the e2e tests passing.

**Pull request merged**
