### PR TITLE
csv-merger: Add text to identify internal CRDs

### PR DESCRIPTION
**Pull request by kshlm**
The DisplayNames and Descriptions of internal CRDs have additional text to indicate they are not to be created or managed by the user.

Currently, this added to all owned CRDs except StorageCluster.

### CODE REVIEW

**Comment by kshlm** [comment]
The descriptions show up in the console as below.
Screenshot_20191113_191818

**Comment by guymguym** [comment]
@kshlm If I may suggest, since there are no new lines in the web page rendering, perhaps it will be more readable putting this disclaimer inside some form of brackets to separate from the rest of the text, like:
```
[This resource is not intended to be created or managed by users] -- A NooBaa system - Create this to start
```

**Comment by travisn** [comment]
What does the StorageCluster description look like? Are we able to move it to be first in the list? Or should we add a message to the Storage Cluster like "**[Create this resource]**"?

**Comment by jarrpa** [comment]
My understanding is that we can't reorder the list, since it just goes by raw CRD name and not the display name.

That said, I like the message text itself. I think it can be left as-is if, in addition, we prepend something like `[Internal]` to all the CRD display names we want the user to avoid.

**Pull request merged**
