### PR TITLE
Add LogCollector to CephCluster CRD

### PR DESCRIPTION
**Pull request by nbalacha**
Updated the CephCluster CRD to include ceph
logcollector settings

Signed-off-by: N Balachandran <nibalach@redhat.com>

### CODE REVIEW

**Comment by nbalacha** [comment]
@leseb , How do I test these changes?

**Review by jarrpa — APPROVED** [review]
/lgtm

**Comment by jarrpa** [comment]
> @leseb , How do I test these changes?

Seems like you should be looking for the Ceph daemon Pods to have an additional logging sidecar container. After that I imagine you'd check somewhere on the system to verify logs are present.

**Pull request merged**
