### PR TITLE
Kms changes for noobaa

### PR DESCRIPTION
**Pull request by aruniiird**
KMS configuration, when provided, will be populated to Noobaa spec.

This is based on #905.

### CODE REVIEW

**Comment by aruniiird** [comment]
Depend on 
PR https://github.com/openshift/ocs-operator/pull/961 , which updates the noobaa-operator
PR https://github.com/openshift/ocs-operator/pull/905 , which adds the KMS changes into ocs-operator

**Comment by obnoxxx** [comment]
This is based on #905 (which is based on #959).
Needs to be rebased and merged after that one.

@aruniiird , @jarrpa 

/hold

holding due to the dependency

**Comment by obnoxxx** [comment]
rebasing does not seem to be needed, since #905 and #959 have merged without further changes

**Comment by obnoxxx** [comment]
strange ci says 31/31 tests passed. but there are failures:
```
 2020/12/16 19:14:19 Executing pod "ocs-operator-bundle-e2e-aws-ipi-conf"
2020/12/16 19:14:24 Container cp-secret-wrapper in pod ocs-operator-bundle-e2e-aws-ipi-conf completed successfully
2020/12/16 19:14:49 Container test in pod ocs-operator-bundle-e2e-aws-ipi-conf completed successfully
2020/12/16 19:14:49 Pod ocs-operator-bundle-e2e-aws-ipi-conf succeeded after 20s
2020/12/16 19:14:58 Executing pod "ocs-operator-bundle-e2e-aws-ipi-conf-aws"
2020/12/16 19:27:54 Container cp-secret-wrapper in pod ocs-operator-bundle-e2e-aws-ipi-conf-aws completed successfully
2020/12/16 19:29:59 pod didn't start running within 15m0s: 
* Container artifacts is not ready with reason PodInitializing
* Container test is not ready with reason PodInitializing
Found 20 events for Pod ocs-operator-bundle-e2e-aws-ipi-conf-aws:
* 0x : Successfully assigned ci-op-f9i504mn/ocs-operator-bundle-e2e-aws-ipi-conf-aws to ip-10-0-149-202.ec2.internal
* 1x kubelet: Failed to create pod sandbox: rpc error: code = DeadlineExceeded desc = context deadline exceeded
* 1x kubelet: Created container cp-secret-wrapper
* 1x kubelet: Started container cp-secret-wrapper
* 1x kubelet: Container image "image-registry.openshift-image-registry.svc:5000/ci-op-f9i504mn/pipeline@sha256:dbbacecc49b088458781c16f3775f2a2ec7521079034a7ba499c8b0bb7f86875" already present on machine
* 1x kubelet: Created container test
* 1x kubelet: Started container test
2020/12/16 19:30:04 pod didn't start running within 15m0s: 
* Container artifacts is not ready with reason PodInitializing
* Container test is not ready with reason PodInitializing
```

etc.

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ocs-operator/961/pull-ci-openshift-ocs-operator-master-ocs-operator-bundle-e2e-aws/1339282115774124032

**Comment by obnoxxx** [comment]
can that be a flake?

**Comment by jarrpa** [comment]
It seems like a flake, but it also seems the test didn't actually run. The 31/31 tests passed message does not refer to the actual number of things being done in the ginkgo test suite.

**Review by jarrpa — APPROVED** [review]
/lgtm

**Pull request merged**
