### PR TITLE
fix(must-gather): Updates gather script to collect pod spec of non-runing pods

### PR DESCRIPTION
**Pull request by ashishranjan738**
This commit updates gather script to collect pod spec of non-running pods.

Signed-off-by: Ashish Ranjan <ashishranjan738@gmail.com>

### CODE REVIEW

**Comment by ashishranjan738** [comment]
Need Backporting for BZ https://bugzilla.redhat.com/show_bug.cgi?id=1775059

**Comment by obnoxxx** [comment]
as discussed, in the future please separate actual changes from cleanups/general improvements of code

**Pull request merged**
