### PR TITLE
ceph: disable many objects warning

### PR DESCRIPTION
**Pull request by agarwal-mudit**
Adding "mon_pg_warn_max_object_skew = 0" to
the [global] section of the defaultRookConfigData var.

Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>

### CODE REVIEW

**Comment by agarwal-mudit** [comment]
For https://bugzilla.redhat.com/show_bug.cgi?id=1926525#c16

**Review by travisn — COMMENTED** [review]
/lgtm

**Review by jarrpa — APPROVED** [review]
/lgtm

**Pull request merged**
