### PR TITLE
Update csv annotation with mcg-standalone feature

### PR DESCRIPTION
**Pull request by afreen23**
Added "mcg-standalone" in the supported features l;ist of operator csv.
This is required so we can have control over the enablement of OCS features in OCP console

Implements https://issues.redhat.com/browse/RHSTOR-2129

Signed-off-by: Afreen Rahman <afrahman@redhat.com>

### CODE REVIEW

**Comment by afreen23** [comment]
Tests failing due to:
```
Init container clonerefs not ready: (state: terminated, reason: "ContainerStatusUnknown", message: "The container could not be located when the pod was terminated") Init container initupload not ready: (state: waiting, reason: "PodInitializing", message: "") Init container place-entrypoint not ready: (state: waiting, reason: "PodInitializing", message: "")
```

**Review by umangachapagain — CHANGES_REQUESTED** [review]
separate go file change and yaml change into separate commits.

**Comment by jarrpa** [comment]
Ad Umanga suggested. However I'm working on a related PR that may make sense to incorporate this into.

**Comment by afreen23** [comment]
Ack. 
Seperated the commits. @umangachapagain @jarrpa

**Review by jarrpa — APPROVED** [review]
/lgtm

**Pull request merged**
