### PR TITLE
Upgrading to apiextensions/v1 for CRDs

### PR DESCRIPTION
**Pull request by umangachapagain**

### CODE REVIEW

**Comment by obnoxxx** [comment]
not sure why ocs-operator-ci is failing - it is working for me, locally.

**Comment by umangachapagain** [comment]
> not sure why ocs-operator-ci is failing - it is working for me, locally.

The tests are failing at `TestCompleteCRD` which validates CRD schema. I think it fails here because it's still validating against the older schema while we have upgraded to newer format.

Since `ocs-operator-bundle-e2e-aws ` passed, it is safe to assume that there's nothing wrong with the CRDs as it is now.

We should probably get rid of this test. WDYT @jarrpa @obnoxxx ?

**Comment by obnoxxx** [comment]
> > not sure why ocs-operator-ci is failing - it is working for me, locally.
> 
> The tests are failing at `TestCompleteCRD` which validates CRD schema. I think it fails here because it's still validating against the older schema while we have upgraded to newer format.

Why are we doing that? Is the test not self-contained? What is different in the ci environment compared to my local checkout?

> Since `ocs-operator-bundle-e2e-aws ` passed, it is safe to assume that there's nothing wrong with the CRDs as it is now.
> 
> We should probably get rid of this test. WDYT @jarrpa @obnoxxx ?

We should mainly make sure that the tests don't somehow use outdated data in the ci?

**Comment by umangachapagain** [comment]
> > > not sure why ocs-operator-ci is failing - it is working for me, locally.
> > 
> > 
> > The tests are failing at `TestCompleteCRD` which validates CRD schema. I think it fails here because it's still validating against the older schema while we have upgraded to newer format.
> 
> Why are we doing that? Is the test not self-contained? What is different in the ci environment compared to my local checkout?
> 
I have no idea about this particular test and how it came into existence. I remember even @jarrpa wasn't sure about this one.
It fails locally as well. Not sure what's different on your system.

> > Since `ocs-operator-bundle-e2e-aws ` passed, it is safe to assume that there's nothing wrong with the CRDs as it is now.
> > We should probably get rid of this test. WDYT @jarrpa @obnoxxx ?
> 
> We should mainly make sure that the tests don't somehow use outdated data in the ci?
>
It's not using outdated data. The behavior is consistent in CI and locally.

**Comment by obnoxxx** [comment]
> > > > not sure why ocs-operator-ci is failing - it is working for me, locally.
> > > 
> > > 
> > > The tests are failing at `TestCompleteCRD` which validates CRD schema. I think it fails here because it's still validating against the older schema while we have upgraded to newer format.
> > 
> > 
> > Why are we doing that? Is the test not self-contained? What is different in the ci environment compared to my local checkout?
> 
> I have no idea about this particular test and how it came into existence. I remember even @jarrpa wasn't sure about this one.
> It fails locally as well. Not sure what's different on your system.

Weird, I could swear it passed locally for me earlier today (on this PR).
But now it fails here too. ;-)

This is the background for the test i have: PR #255 .

> > > Since `ocs-operator-bundle-e2e-aws ` passed, it is safe to assume that there's nothing wrong with the CRDs as it is now.
> > > We should probably get rid of this test. WDYT @jarrpa @obnoxxx ?

Well, it's safe to assume there's nothing wrong just because this test fails, b/c it was apparently written against the old style CRD. In order to move forward, we could disable the test for now and investigate a bit more what it was trying to achieve, why it fails now, and whether it's worth adapting it?

**Comment by umangachapagain** [comment]
#918 skips the CRD Validation tests.

**Comment by obnoxxx** [comment]
I had a typo in my last comment, it was PR #25 , not #255 - updated ;-)

**Comment by obnoxxx** [comment]
> #918 skips the CRD Validation tests.

Great, thanks! Now that that is merged, we can rebase this PR and hopefully see the unit tests pass.

**Review by obnoxxx — APPROVED** [review]
/lgtm

**Pull request merged**
