### PR TITLE
Bug 1764984: Update Rook-Ceph image (1.1.4) and NooBaa image (2.0.3)

### PR DESCRIPTION
**Pull request by jarrpa**
The names of the secrets used by StorageClasses for the Rook Ceph CSI drivers have been updated to follow the changes in Rook

This is an alternate PR to #231, due to holiday schedules. Removes #205, as that is not related to this BZ and is not relevant to the release.

### CODE REVIEW

**Comment by obnoxxx** [comment]
@jarrpa if this is a replacement for #231, then it should probably mention the secret name thing in the PR title/description, as that's the main original point of #231.

**Comment by jarrpa** [comment]
Done

**Comment by guymguym** [comment]
Hi can you update to 2.0.4?

**Comment by jarrpa** [comment]
That should be done in master first, then backported as a separate PR.

**Comment by obnoxxx** [comment]
There's a dependency between this and a possible backport of #216 / #244: While those PRs are expected to test the ocs-operator-e2e-aws failures, backporting that one first will create unnecessary conflict resolutions. So I'm moving forward with merging this one and then going to backport #244 on top for cleaner backports.

/hold cancel

**Pull request merged**
