### PR TITLE
[WIP] Adding Client for OCS using client-gen

### PR DESCRIPTION
**Pull request by umangachapagain**
Using the client-gen to generate an ocs client that simplifies CRUD operations on ocs-operator CRs such as StorageCluster.

### CODE REVIEW

**Comment by mhrivnak** [comment]
Just keep in mind that the clientset has no cache. The controller-runtime client caches reads by default, the importance of which cannot be overstated for production use.

Are you adding this just for testing purposes? In what circumstance do you find it to be a better fit than the controller-runtime client?

**Comment by umangachapagain** [comment]
> Are you adding this just for testing purposes?
>
I was just experimenting to see what controls the clientset provides.

> In what circumstance do you find it to be a better fit than the controller-runtime client?
>
`controller-runtime client` was completely off my mind.
I do not have enough knowledge about either to answer this. So, I'll start digging deeper into it.

@davidvossel What do you think? `controller-runtime client` does satisfy our use-case for testing.

**Comment by davidvossel** [comment]
> @davidvossel What do you think? controller-runtime client does satisfy our use-case for testing.

is there a way to use the controller-runtime client without caching? The tests need direct access to the k8s apiserver in a way that doesn't involve a reconcile loop or caching.

**Comment by mhrivnak** [comment]
> > @davidvossel What do you think? controller-runtime client does satisfy our use-case for testing.
> 
> is there a way to use the controller-runtime client without caching? The tests need direct access to the k8s apiserver in a way that doesn't involve a reconcile loop or caching.

Yes. When you create a new client manually, it defaults to non-caching. Here's an example of that: https://github.com/operator-framework/operator-sdk/blob/947a464/pkg/leader/leader.go#L57-L65

When you create a `Manager`, it sets up a caching client that gets handed to every `Controller`, and that's the client you normally use from a `Reconcile` call.

**Comment by davidvossel** [comment]
> Yes. When you create a new client manually, it defaults to non-caching. Here's an example of that: https://github.com/operator-framework/operator-sdk/blob/947a464/pkg/leader/leader.go#L57-L65

Oh, interesting. Thanks for the tip!

In that case the only value I can see of generating the ocs-operator client would be if there was an external tool that wanted to consume our client api. I'm not aware of any.

**Comment by umangachapagain** [comment]
> In that case the only value I can see of generating the ocs-operator client would be if there was an external tool that wanted to consume our client api. I'm not aware of any.
>
Agreed. I will abandon this PR for now and explore controller-runtime/client.
If needed later, we can revive this.

**Pull request closed without merging**
