### PR TITLE
generate relatedImages in ocs CSV

### PR DESCRIPTION
**Pull request by dannyzaken**
Fixes BZ 1798052 - https://bugzilla.redhat.com/show_bug.cgi?id=1798052

* `relatedImages` is not part of `ClusterServiceVersionSpec` and is not marshaled as part of the struct marshaling
* added a modifier func to `marshallObject` to modify unstructured fields in the yaml
* adding any non empty image to `relatedImages`

### CODE REVIEW

**Comment by andrewschoen** [comment]
Will ``make gen-release-csv`` or ``make source-manifests`` update relatedItems if the appropriate environment variables are provided?

**Comment by dannyzaken** [comment]
@andrewschoen yes. I used `make gen-latest-csv` to generate `ocs-operator.v4.3.0.clusterserviceversion.yaml`. it eventually uses the same scripts as `make gen-release-csv` and `make source-manifests`

**Comment by dannyzaken** [comment]
@davidvossel @jarrpa @obnoxxx any idea why the tests are failing?
I also would appreciate your review. this PR is required for the disconnected environment testing

**Comment by obnoxxx** [comment]
@dannyzaken not sure. the ci was having severe issues lately.

**Comment by jarrpa** [comment]
I see that ocs-operator-ci passed just now, and I'm guessing `ci/prow/images` will too. ocs-operator-e2e-aws will likely fail.

@dannyzaken I'd like to make sure something like this passes the functional tests. Could you take some time to run the functional tests on your own environment to verify the changes work? I'll LGTM after that.

**Comment by dannyzaken** [comment]
@jarrpa I ran functests on my env. upgrade test failed. is that expected?
```
Summarizing 1 Failure:

[Fail] Cluster upgrade ocs [BeforeEach] upgrade cluster and verify deployment status
/Users/dannyzaken/code/go/src/github.com/openshift/ocs-operator/functests/setup_teardown.go:70

Ran 7 of 7 Specs in 2871.218 seconds
FAIL! -- 6 Passed | 1 Failed | 0 Pending | 0 Skipped

```

this PR shouldn't affect the deployment or upgrade of OCS, It only adds the `relatedImage` field to the CSV. this field is not part of the `ClusterServiceVersion` spec and is not even applied to the CR in the cluster

**Comment by jarrpa** [comment]
The upgrade test has been giving us problems. Seeing the other 6 pass is good enough for me! Let me know when you rebase and I'll lgtm.

**Comment by dannyzaken** [comment]
@jarrpa rebased

**Pull request merged**
