### PR TITLE
added rook-csi-resizer to relatedImages

### PR DESCRIPTION
**Pull request by dannyzaken**
* rook-csi-resizer image was added to `csv-merger.go` without adding it to the `relatedImages`. this prevents it from being automatically mirrored in a disconnected environment.
*  without the fix disconnected env setup requires another manual step

### CODE REVIEW

**Comment by humblec** [comment]
lgtm from my end too.

**Comment by dannyzaken** [comment]
@obnoxxx rebased

**Comment by obnoxxx** [comment]
Rebased it b/c @dannyzaken is not available.

Strangely, I needed to include a csv update, but this only updates the hash. :thinking:

**Comment by obnoxxx** [comment]
at least `make verify-latest-csv` was failing locally for me and I had to run this.

**Pull request merged**
