### PR TITLE
must-gather:log the total time taken by collection script

### PR DESCRIPTION
**Pull request by rajatsing**
this pr will fix the issue where the collection script was not able to log the total time taken by the must gather collection script

Signed-off-by: RAJAT SINGH <rajasing@redhat.com>

### CODE REVIEW

**Comment by rajatsing** [comment]
This PR is the fix of #1009 this logs the total time taken by the collection script in seconds, I have t disable the shellcheck in order to achieve that, in later releases, I will make the time taken in the format of `hh:mm:ss` but for now/this relase, this will work.

**Comment by rajatsing** [comment]
This is how the `gather-debug.log` file ends like

```
total time taken by collection was 351 seconds
collection ended at: 09:31:47 PM
deleting empty files
```

**Comment by rajatsing** [comment]
Removed the shellchecks, thanks @jarrpa

**Review by jarrpa — APPROVED** [review]
Excellent. I do so like clean commits.

/lgtm

**Pull request merged**
