### PR TITLE
UnitTests: Add Uninstall tests

### PR DESCRIPTION
**Pull request by iamniting**
Add remaining tests for uninstall_reconciler.go

cc: @raghavendra-talur

### CODE REVIEW

**Review by jarrpa — CHANGES_REQUESTED** [review]
For all these tests, use a proper table-driven struct (in readable format as requested in https://github.com/openshift/ocs-operator/pull/794#discussion_r505915347), don't just loop over a list of booleans with no names.

**Comment by iamniting** [comment]
I am planning to work on this once others are merged.

**Comment by jarrpa** [comment]
Actually, can we just use one PR? That'll save everyone a lot of time. Close the other ones and we can focus on this one.

**Comment by iamniting** [comment]
> Actually, can we just use one PR? That'll save everyone a lot of time. Close the other ones and we can focus on this one.

Done

**Review by jarrpa — APPROVED** [review]

**Pull request merged**
