### PR TITLE
Fix OperatorGroup indentation in deploy-with-olm.yaml

### PR DESCRIPTION
**Pull request by rohantmp**
Signed-off-by: Rohan CJ <rohantmp@redhat.com>

### CODE REVIEW

**Comment by rohantmp** [comment]
I think we need a way to disable CI on things that CI doesn't test for. Does CI test deploy-with-olm.yaml?

**Comment by obnoxxx** [comment]
@rohantmp  wrote:
> I think we need a way to disable CI on things that CI doesn't test for. Does CI test deploy-with-olm.yaml?

I think it *should* test the syntax of yamls. 

And yes, the new ocs-operator-e2e-aws test does test the deployment with this yaml file! :-)

/ok-to-test

**Comment by rohantmp** [comment]
Closing. Will fix in: https://github.com/openshift/ocs-operator/pull/102

**Comment by obnoxxx** [comment]
@rohantmp wrote:
> Closing. Will fix in: #102

not closed yet :-)

**Pull request closed without merging**
