### PR TITLE
Bug 1778805: Backport 4.2 - Bump noobaa operator v2.0.9 + core v5.2.11

### PR DESCRIPTION
**Pull request by guymguym**
Backport of #348

Thanks @kshlm for the help!

Due to #347 we couldn't update go.mod but there is no change in the API so will update once that issue is resolved.

### CODE REVIEW

**Comment by kshlm** [comment]
@guymguym is there a bz for this?
/ok-to-test

**Comment by guymguym** [comment]
@nimrod-becker bz?

**Comment by nimrod-becker** [comment]
@kshlm @obnoxxx 
Since the BZ was fixed with the merge into the noobaa-operator branch and the DS build already takes the new version. How do we handle this? We keep on hitting the same problem :)
The images and versions are mainly for consuming this repo and not for DS builds, can we remove the BZ requirement?

**Comment by kshlm** [comment]
We don't want to remove the BZ restriction on this branch. Especially not now so close to GA. If we can't get a bz for this right now, then my preference is to hold this till we have another bz that needs to update the images and do it then.

**Comment by kshlm** [comment]
If this is affecting any testers, then we should really encourage them to use the downstream builds instead. It's just a matter of changing one word in the registry image (`s/ocs-dev/rhceph-dev/`) for the catalogsource.

**Comment by obnoxxx** [comment]
we can "misuse" an existing BZ to get this into ocs-operator... ;-)

@kshlm - what do you think?

**Pull request merged**
