### PR TITLE
Bug 1849105: [release-4.5] StorageCluster: remove node taints during uninstall

### PR DESCRIPTION
**Pull request by raghavendra-talur**
This is a cherry-pick of #560 

To be merged after

#575 
#574 
#576

### CODE REVIEW

**Comment by raghavendra-talur** [comment]
@jarrpa @obnoxxx Please take a look.

**Comment by jarrpa** [comment]
Needs a rebase.

**Comment by raghavendra-talur** [comment]
@jarrpa This is now ready for merge.

**Pull request merged**
