### PR TITLE
storagecluster: Change event type from error to warning

### PR DESCRIPTION
**Pull request by iamniting**
Fix Error via changing event type
"E0210 23:17:48.027136       1 event.go:334] Unsupported event type: 'Error'"

Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

Fix https://bugzilla.redhat.com/show_bug.cgi?id=1913357#c8

### CODE REVIEW

**Review by raghavendra-talur — APPROVED** [review]

**Review by jarrpa — CHANGES_REQUESTED** [review]
Can you explain why this is needed, namely why EventTypeError was used even though it's invalid?

**Comment by iamniting** [comment]
> Can you explain why this is needed, namely why EventTypeError was used even though it's invalid?

When we have sent the PR before we did not realize this. This came recently as part of a failed QA Bug https://bugzilla.redhat.com/show_bug.cgi?id=1913357#c8

**Review by jarrpa — APPROVED** [review]
A bit odd that we didn't catch this ahead of time, but I'm willing to skip a deeper RCA.

/lgtm

**Pull request merged**
