### PR TITLE
New CSV: Bump rook version to v1.1.0-beta.1 and enable it's features

### PR DESCRIPTION
**Pull request by rohantmp**
Changes: Enable Fencing, Fix Indentation, Enable pg_autoscaler

### CODE REVIEW

**Comment by rohantmp** [comment]
@kshlm can we ok-to-test this? How do I get privs to ok-to-test and retest?

**Comment by kshlm** [comment]
/ok-to-test

@rohantmp You need to become a part of the Openshift oragnization to get access to the test commands.

**Comment by rohantmp** [comment]
@kshlm tests passed

**Comment by kshlm** [comment]
@rohantmp Have you verified the new rook image is working and deployment isn't broken?

**Comment by rohantmp** [comment]
@kshlm I'll just test it once more with a full CSV based deployment. Just managed to unbreak my setup from a silly mistake a few minutes ago.

**Comment by obnoxxx** [comment]
@rohantmp wrote:
> @kshlm I'll just test it once more with a full CSV based deployment. Just managed to unbreak my setup from a silly mistake a few minutes ago.

How did the tests go?
And this needs rebasing/conflict resulution now.

**Comment by rohantmp** [comment]
Ran into some issues testing yesterday. The changes seemed to function fine, but one mon of 3 was not coming up. Will rebase and see if that solves the issue.

Will also update to enable PG autoscaler.

**Comment by rohantmp** [comment]
Anyone wanting to test this CSV can use this yaml: https://hastebin.com/efemakeqes.makefile

I think  everything that I am enabling works fine: Fencing, pg_autoscaler

I am running into some issues with the deployment such as one OSD failing to properly come up even though the pod comes up. I am checking if this is an existing(occuring only sometimes) issue or if it comes from the rook image.

**Pull request merged**
