### PR TITLE
ocs: update dependencies for rook image version

### PR DESCRIPTION
**Pull request by nbalacha**
Signed-off-by: N Balachandran <nibalach@redhat.com>

### CODE REVIEW

**Review by umangachapagain — COMMENTED** [review]
Updating Rook version shouldn't affect StorageCluster CRD.
Can you check why this is happening?

**Comment by nbalacha** [comment]
> Updating Rook version shouldn't affect StorageCluster CRD.
> Can you check why this is happening?

I don't know why this is happening but the CRDs were changed I ran make gen-latest-csv  and hence included them as well.

**Review by umangachapagain — APPROVED** [review]

**Pull request merged**
