### PR TITLE
Bug 1762335: csv: Change OCS_IMAGE to quay.io/ocs-operator:4.2.0

### PR DESCRIPTION
**Pull request by kshlm**

### CODE REVIEW

**Comment by davidvossel** [comment]
what were the details around why we can't auto-detect the git branch? i don't fully understand

**Comment by kshlm** [comment]
> what were the details around why we can't auto-detect the git branch? i don't fully understand

Nothing really. I wanted to get this simple change in for the automated builds.

**Comment by davidvossel** [comment]
/lgtm

we'll try and follow up with another pr in master that does the tag detection automatically for release branches so we don't have to keep updating this value for each release branch... during the investigation into how to do the automation there, it turns out this isn't trivial, so it needs some more thought. 

For now, this works fine for the 4.2 branch.

**Comment by kshlm** [comment]
/hold

Need to figure out the missing labels. Or remove the requirement.

**Pull request merged**
