### PR TITLE
updates openshift/api to enable Quickstart APIs for Console

### PR DESCRIPTION
**Pull request by umangachapagain**
Updating openshift/api dependency to release-4.7.
It still supports Kubernetes 1.19.z and adds Quickstart API required
by the OCS Console.

Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>

### CODE REVIEW

**Comment by umangachapagain** [comment]
@dannyzaken I see NooBaa is dependent on `openshift/api/routes` v3, will this cause any trouble?

**Comment by dannyzaken** [comment]
I am not familiar with the changes and how compatible it is. 
@nb-ohad do you have any idea if it will affect noobaa-operator?

**Comment by nb-ohad** [comment]
@dannyzaken not really, but why does it matter? We are not exposing routes apis in our CRDs so I don't see an issue here

**Review by jarrpa — APPROVED** [review]
/lgtm

**Pull request merged**
