### PR TITLE
storagecluster: Append "-rook-ceph" to name of created CephCluster

### PR DESCRIPTION
**Pull request by kshlm**
This hopefully helps fix the failures in long running, idle clusters.

### CODE REVIEW

**Comment by kshlm** [comment]
I have a built images for testing which can be deployed with https://gist.github.com/kshlm/a3eaf37bb2d06788f57654be9f889223/raw/deploy-with-olm.yaml

**Comment by kshlm** [comment]
> Generally looks good. I'd rather append `-cephcluster`, instead.

I did consider it, but dropped it because the CephCluster would be names `ocs-storagecluster-cephcluster` which doesn't read nice.

**Comment by jarrpa** [comment]
> > Generally looks good. I'd rather append `-cephcluster`, instead.
> 
> I did consider it, but dropped it because the CephCluster would be names `ocs-storagecluster-cephcluster` which doesn't read nice.

Personally that looks much nicer than `ocs-storagecluster-rook-ceph`. Also, it's misleading to label a CephCluster as `rook-ceph`, since that's technically the operator. I'm willing to entertain other options, but thus far I don't like the `-rook-ceph` ending.

**Comment by travisn** [comment]
What about `ocs-rook-cephcluster`? Is the naming the only thing blocking this merge? We need to start the clock ticking on the testing to even see if this will help.

**Comment by jarrpa** [comment]
Fine, I'll fix this later myself. We may need to revert it anyway if it doesn't fix anything.

/lgtm

**Pull request merged**
