### PR TITLE
Switch to use go modules

### PR DESCRIPTION
**Pull request by davidvossel**
Go modules makes managing go dependencies much more efficient.

Here's the new flow.

- `make deps-update` will pick up and vendor any changes automatically for you and update`go.mod` and `go.sum` 
- after running `make deps-update`, commit any changes to go.sum, go.mod, and the vendor directory that occur.

### CODE REVIEW

**Comment by davidvossel** [comment]
> This doesn't seem like a good idea. OCP 4.2 is based on Kubernetes 1.14, so we should probably be developing against those APIs.

@jarrpa  right now (before my go module change) we were developing against kubernetes 1.12 packages. I was able to get us up to 1.13 without requiring any code changes. Going to 1.14 breaks our build though.

It wouldn't be a bad idea for us to move to the 1.14 apis at some point, but that isn't  a requirement to target ocp 4.2. The apis are backwards compatible. Unless we're using functionality that 1.14 introduces (which we aren't) then this isn't urgent.

**Comment by jarrpa** [comment]
Ah, all right. Good enough.

/lgtm

**Pull request merged**
