### PR TITLE
Ints for requests and limits are valid

### PR DESCRIPTION
**Pull request by mmgaggle**
Mirror what is done by Kube

https://github.com/kubernetes-sigs/controller-tools/pull/381/files#diff-83f69cf64da4a50ca73fc80e1de20c25R1774-R1778

### CODE REVIEW

**Comment by sttts** [comment]
Lgtm.

**Comment by JohnStrunk** [comment]
Isn't the CRD generated automatically from *_types.go by operator-sdk?
I think we need to add the proper annotations there such that the CRD is generated correctly (if possible).

**Comment by umangachapagain** [comment]
> Isn't the CRD generated automatically from *_types.go by operator-sdk?
> I think we need to add the proper annotations there such that the CRD is generated correctly (if possible).

Yes.
While we want to reach this state, directly changing the CRD spec will not work.
There are multiple steps to get this done properly.

**Comment by umangachapagain** [comment]
Added complete fix here: https://github.com/openshift/ocs-operator/pull/659

**Pull request closed without merging**
