### PR TITLE
unit testing for ocsinitialization_controller

### PR DESCRIPTION
**Pull request by jeremyary**
- Reconciler init moved up to controller package level to allow test injection of [k8s fake client](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/fake/client.go) 
- reconciler interface implementation check moved to test
- multiple other tests for reconcile logic added

### CODE REVIEW

**Comment by jeremyary** [comment]
Requested changes to commits done.

**Comment by jeremyary** [comment]
hmm, I'll take a look at what lint is kicking back about Add 1st thing Monday.

**Comment by jeremyary** [comment]
Add() func comment changed to 'Add' from 'add' for lint, rebased again. Are you guys running lint locally somehow as part of dev cycle? Thanks!

**Comment by jeremyary** [comment]
Note: tests will be affected by https://github.com/openshift/ocs-operator/pull/66 if that merges in first (refactoring init code in controllers)

**Comment by obnoxxx** [comment]
@jarrpa, looks like this is good to go now? (you gave lgtm earlier on, and now it's passing tests)

**Comment by jarrpa** [comment]
Oh! I didn't see the label got removed, sorry.

/lgtm

**Pull request merged**
