### PR TITLE
Must-gather: Add SCC to cluster-scoped must-gather

### PR DESCRIPTION
**Pull request by jackyalbo**
Signed-off-by: jackyalbo <jalbo@redhat.com>

### CODE REVIEW

**Review by crombus — CHANGES_REQUESTED** [review]
Thanks for the PR. Code changes looks good. 
I have a request in commit msg 
1) Please add ```Must-gather: ``` tag in the beginning 
2) Instead of adding ->add (optional)

**Comment by jackyalbo** [comment]
> Thanks for the PR. Code changes looks good.
> I have a request in commit msg
> 
> 1. Please add `Must-gather: ` tag in the beginning
> 2. Instead of adding ->add (optional)
Thanks for the feedback - fixed

**Review by crombus — APPROVED** [review]

**Pull request merged**
