### PR TITLE
initial commit - Creating NooBaa resources in OCS operator

### PR DESCRIPTION
**Pull request by dannyzaken**
CC: @guymguym

Initial PR integrating NooBaa with OCS operator

* Updated vendor and Gopkg to include noobaa-operator
* Added default storage class for noobaa OBC provisioner in init controller
* Added `ensureNoobaaSystem` to StorageCluster reconciler

### CODE REVIEW

**Comment by dannyzaken** [comment]
I still need to test it and will appreciate some help with running the operator, mainly where can I get ceph CRDs yamls so I can get it to run

**Comment by guymguym** [comment]
> I don't think `ensureNooBaaSystem()` belongs as part of the StorageCluster `Reconcile()`. Will it ever be the case that we want more than one NooBaa system in a given installation of OCS? I was thinking we would just have one NooBaa system and then different StorageClasses to make use of different backing stores for different Ceph clusters (if we even go that far).

@jarrpa I think reconcile of StorageCluster is what we want, but lets try to describe the relation between these CR's: 1 StorageCluster => 1 CephCluster + 1 NooBaa - is that how you see it or is there a reason to make anything more complex in these relations?

**Comment by jarrpa** [comment]
If anything I think that relationship is too complex already. Currently, 1 StorageCluster -> 1 CephCluster, and we want to be able to expand to multiple CephClusters in the future. But I don't see a need for more than one NooBaa system per OpenShift cluster, as such it makes no sense to tie it to StorageCluster reconciliation.

**Comment by mykaul** [comment]
> If anything I think that relationship is too complex already. Currently, 1 StorageCluster -> 1 CephCluster, and we want to be able to expand to multiple CephClusters in the future. But I don't see a need for more than one NooBaa system per OpenShift cluster, as such it makes no sense to tie it to StorageCluster reconciliation.

I'm not sure why we'd want only one Noobaa if we have multiple OCS clusters. Still unsure what are the use cases for multiple OCS clusters, but they may apply to Noobaa as well.

**Comment by guymguym** [comment]
I actually though the opposite - why do you need multiple CephClusters per openshift cluster?

So you want the StorageCluster to just be a wrapper to rook-ceph? OK, so which CRD represents an "OCS deployment" - aka the deployment of ceph and noobaa?

**Comment by jarrpa** [comment]
It's not that I want a StorageCluster to JUST be a wrapper for a CephCluster, that's merely what it is right now.

The desire for multiple CephClusters per OCS installation is a request we've had from the beginning that hasn't been completely given up on, mostly for the purposes of completely isolating distinct pools of storage for different tiers of stability and risk management.

I've heard of no such need or request for NooBaa, and I didn't want to introduce it if it wasn't being asked for. As such, I was thinking the OCS operator itself would just create an initial NooBaa system and leave it alone forever. I wasn't seeing anything in the CRD that warranted any monitoring, either.

**Comment by guymguym** [comment]
@jarrpa That's a great idea because it removes another user step! But actually there is no need to do anything at all in the OCS operator. I'll just make the noobaa's operator start by immediately creating the default noobaa CR and then followup by deploying a system. If we ever need more systems we just deploy more operators on other namespaces. Thanks! 
+@tamireran @dannyzaken

**Comment by mykaul** [comment]
> It's not that I want a StorageCluster to JUST be a wrapper for a CephCluster, that's merely what it is right now.
> 
> The desire for multiple CephClusters per OCS installation is a request we've had from the beginning that hasn't been completely given up on, mostly for the purposes of completely isolating distinct pools of storage for different tiers of stability and risk management.
> 
> I've heard of no such need or request for NooBaa, and I didn't want to introduce it if it wasn't being asked for. As such, I was thinking the OCS operator itself would just create an initial NooBaa system and leave it alone forever. I wasn't seeing anything in the CRD that warranted any monitoring, either.

Isolating storage classes need to be done via CRUSH map configuration. Stability is not obtained by needing to upgrade and manage a set of clusters - it just adds management overhead on a regular basis (but I do understand the request).

**Comment by jarrpa** [comment]
> Isolating storage classes need to be done via CRUSH map configuration. Stability is not obtained by needing to upgrade and manage a set of clusters - it just adds management overhead on a regular basis (but I do understand the request).

I'm can't say I disagree with you, merely acknowledging that the issue hasn't been fully put to bed yet, as such I've kept the StorageCluster design flexible.

**Comment by jarrpa** [comment]
> I'll just make the noobaa's operator start by immediately creating the default noobaa CR and then followup by deploying a system. If we ever need more systems we just deploy more operators on other namespaces. Thanks!

Requiring a unique operator for new instances of the same thing is antithetical to the operator pattern, and sounds like a mess to deal with from an OLM standpoint, but that's a discussion for another time. :) At this stage I don't entirely care what creates the NooBaa system, since we only need one.

**Comment by mhrivnak** [comment]
> > I'll just make the noobaa's operator start by immediately creating the default noobaa CR and then followup by deploying a system. If we ever need more systems we just deploy more operators on other namespaces. Thanks!
> 
> Requiring a unique operator for new instances of the same thing is antithetical to the operator pattern, and sounds like a mess to deal with from an OLM standpoint, but that's a discussion for another time. :) At this stage I don't entirely care what creates the NooBaa system, since we only need one.

Running a unique deployment of the operator for each NooBaa CR is not a good fit for the operator pattern, particularly as it's implemented in openshift.

If the NooBaa CR is always going to be a singleton (there will only be one per kubernetes cluster), then it would be great for the noobaa-operator to auto-create that CR on startup and take measures to restrict creation of additional instances.

But if it may be desirable to create more than one NooBaa CR on the same kubernetes cluster, then it is best to let something/someone else create those CRs as needed and stick with a single deployment of the operator. In this case, it seems like the ocs-operator is the natural choice to manage those CRs and decide if/when they need to be created.

**Comment by guymguym** [comment]
> Running a unique deployment of the operator for each NooBaa CR is not a good fit for the operator pattern, particularly as it's implemented in openshift.

@mhrivnak Why not? Sounds like a very good pattern to me - very simple to use and does exactly what the user intended.

**Comment by dannyzaken** [comment]
Thanks all.
closing the PR for now. will open a new PR with the storage class and noobaa CSV additions once PR #8 is merged

**Comment by mhrivnak** [comment]
> > Running a unique deployment of the operator for each NooBaa CR is not a good fit for the operator pattern, particularly as it's implemented in openshift.
> 
> @mhrivnak Why not? Sounds like a very good pattern to me - very simple to use and does exactly what the user intended.

Within the operator ecosystem, we're using the kubernetes API as the way to deploy applications in a declarative way. An operator is three things: a CRD that describes the operand, a controller, and operation logic coded into the controller. In order to deploy Wordpress, I would create an instance of the Wordpress CR and describe in the `Spec` what I want it to look like. As the persona who is deploying wordpress, I have no involvement with the operator. Much of the point of the pattern is to enable end users to deploy fully-managed workloads without having to worry about who or what is doing the management, giving a similar experience to using a managed service on a public cloud. There is a basic and fundamental expectation that the API to deploy a thing is the CR that represents the thing.

Controllers and operators are inherently designed to reconcile and manage multiple instances of their CR. It's the default behavior. We have created some singletons in a case where we know there should only be one instance of a thing deployed for the entire k8s cluster, but that is already bending the operator pattern in an awkward direction.

Now enter noobaa. The API to deploy noobaa should be the Noobaa CR. That is what users, customers, developers, admins, tooling, the UI, etc will expect. If you instead made the API for deploying noobaa a Deployment, which needs to run a particular operator with a particular image, service account, configuration, etc. that has nothing to do with describing a noobaa deployment. If the user wants to deploy noobaa, let them just describe that through the Noobaa CR.

What if there are no settings on the Spec for them to set? Even in that case, the CR is the API for managing the lifecycle of the noobaa deployment. The `Status` gives the user an understanding of how noobaa is doing and what management actions may be required. Removing noobaa should simply involve deleting the CR. **The full lifecyle of a noobaa deployment should be managed via a CR**.

In terms of OCS, we need the ability to deploy rook/ceph, noobaa-operator, and any other operator that joins the product as a single CSV. This is a pattern sometimes called a "meta-operator", where we have one parent operator (ocs-operator in this case) that, from a packaging and installation perspective, is a composite of several other operators. I can elaborate more on this pattern if that would be helpful, but for now let's take it as a given. The installation, upgrade (particularly important), and removal of OCS will be managed through a single CSV. A user will install OCS, and the result will be that all the operators they need will be installed. An upgrade has a definitive state; either the operator upgraded or it didn't. It's either healthy or it's not. Etc. This is what the operator tooling is setup to manage, and so this is a requirement. There is not a way to facilitate installation of additional on-demand operators in that approach, nor do we have another approach we can take that would.

There is also the issue of cost. There is a real cost to the end user for running extra Pods. The total footprint of operators in the openshift ecosystem is quite large, and we should take that seriously. When there is a reasonable opportunity to reduce that footprint, it is a good idea to do so. In this case, it would be a shame to require an extra operator pod per CR unless absolutely necessary.

Lastly, I'm not aware of any other operator that requires a dedicated operator for each CR. Noobaa-operator would be an outlier in that respect, and I strongly encourage you not to follow such a pattern.

**Comment by guymguym** [comment]
Hi @mhrivnak, thanks for the detailed description.
/cc @jarrpa @tamireran @dmesser 

I am aware of the current standard of the operator pattern, but I don't see it as perfect yet for every use case. Let me explain:

1. We are still suggesting that the NooBaa CR will be used to manage the lifecycle, spec and status of the NooBaa deployment - we just auto-create the CR with defaults when the operator starts.

2. The case of creating wordpress vs creating NooBaa/Ceph is not really similar. Most users will never be interested to deploy NooBaa/Ceph on their own, and will request the deployment from their admin.

3. The cost of an operator pod with 100m cpu and 100MB memory is negligible for deployments of such storage systems.

4. The pattern of an operator does not specify that the controller must be a singleton Pod in the cluster. A "controller" is merely a reconcile logic. The suggestion is to deploy that logic as many times as deployments are needed. The vast majority of cases is just 1 deployment and even when there will be more we expect just a couple of deployments per cluster.

5. Essentially we are using the OLM operator as our meta-operator, and by creating a `Subscription` we initiate the deployment. OLM install is the day-1 zero-config operation, and any further edits of the NooBaa CR spec are day-2 operations.

The benefit of this pattern is that there is a real separation of the deployments:
* from failure tolerance perspective failures of one operator will not affect other systems.
* from security perspective the operator can limit its watch and RBAC to just a Role and not require a ClusterRole in order to watch Secrets from all namespaces for example - which IMHO is a bad clusterPermission to require. If your operator reconciles by creating StatefulSets / Pods / Secrets / Services etc, the operator pattern that watches all namespaces will require a ClusterRole with permissions to full control of those core resources on **all** namespaces, which sounds incredibly risky, isn't it?

I am not convinced that my suggestion is good, but I am also not sure the "standard" operator pattern is good for our deployment use case.

Will be happy to continue the discussion! Thanks

**Comment by tamireran** [comment]
@guymguym I think that the suggestion makes sense. The provided security reasoning is a good point. 
I agree that most of the deployments will require only a single  NooBaa deployment, and the suggested solution allows the scale to more than one deployment. 
We may change this behavior along the way, based on customer feedback, but currently, our first priority is to deliver the most usable solution, and your suggestion looks like a good fit. 

I'm ok if you decide on another solution suggested by others, but suggest to push the first PR asap, to allow longer time for QE.

**Comment by dmesser** [comment]
@tamireran @guymguym regarding your last point - you could argue that running any Operator is attached to some risk. Eventually these are API extensions that introduce global resources (CRD). Your use case of having multiple Operator deployments managing different CRs is supported by OLM.

That said, I concur with Michael that what you describe is somewhat different to the usual UX when deploying and using Operators. Technically there is nothing wrong with auto-creating a CR upon start - this is even what we suggested as some developers looking for patterns to have an initial "Install CRD" that configures some system-level environment. Upon closer investigation we noticed that what they are doing is creating an Operator which deploys another Operator - a story for another time.

Here I would suggest to just have OLM deploy the NooBaa Operator which also deploys a validation admission webhook which eventually makes the decision on whether or not the CR would be allowed. This is how you can implement singleton behavior. Also this retains the usual UX (Operators don't change the state until their APIs are used) and still allows for the behavior you are looking for.

**Comment by dannyzaken** [comment]
reopening the PR
after a discussion with @tamireran there should be a 1:1 relation between OCS instance and noobaa

**Comment by guymguym** [comment]
@jarrpa I checked again with @tamireran on the product design, and as I understand what we need to provide is that the OCS operator will start, and then there will be an OCS CR that will deploy both Ceph and NooBaa. If you have questions on the design we should verify it with Eran. Thanks

**Comment by tamireran** [comment]
> This PR still does not ensure a 1-to-1 mapping between OCS installation and NooBaa system. The NooBaa system needs to be deployed during the OCSInitialization reconcile, not the StorageCluster reconcile.

@jarrpa, The desired behavior is to deploy the operator in parallel or after the storagecluster reconcile. There is a dependency on the storage class as well as RGW on-prem, and I want to avoid a situation where we have a pending NooBaa system until we have the storage class deployment. 

Please approve the PR
Thanks

**Comment by mhrivnak** [comment]
> > This PR still does not ensure a 1-to-1 mapping between OCS installation and NooBaa system. The NooBaa system needs to be deployed during the OCSInitialization reconcile, not the StorageCluster reconcile.
> 
> @jarrpa, The desired behavior is to deploy the operator in parallel or after the storagecluster reconcile. There is a dependency on the storage class as well as RGW on-prem, and I want to avoid a situation where we have a pending NooBaa system until we have the storage class deployment.

All operators that are part of OCS will be deployed at approximately the same time by OLM. We should not depend on the order of operators getting deployed. But this PR doesn't seem to involve deploying operators, so maybe you are talking about the operands?

If noobaa-operator cannot do what it needs until some other things exist, can it simply wait for those things to exist? It's normal for an operator to either:

1. wait in main.go until a particular API becomes available, then start controllers
2. re-queue a resource that's being reconciled if the operator needs to wait more time for something to happen

Is one of those not sufficient for the situation you mentioned?

**Comment by jarrpa** [comment]
There is no dependency here that would prevent the NooBaa operator from starting, so they will still deploy in parallel. Moving this function to the OCS initialization will introduce no further dependency, and in fact will allow NooBaa to start without waiting for Ceph configuration, which I believe is desired. Further, the StorageClasses can be arbitrarily created at any time, the only consequence is that any PVC requests will remain pending until the configured provisioner exists / succeeds.

Thus, I still want this to be part of the operator (basically, product) initialization, rather than a StorageCluster initialization.

**Comment by guymguym** [comment]
@jarrpa but ocs initialization means that this is part of the operator install flow, right? This is not what product design requires. It requires us to i stall NooBaa with Ceph when instantiating an OCS deployment. Can you please explain how your preference meets this requirement? Thanks?

**Comment by jarrpa** [comment]
Okay, so I've acquiesced to the current proposed design of having one NooBaaSystem per StorageCluster. However, I still believe this PR is incorrect. The reason is because we are also implementing a StorageClassInitialization CRD that will take care of doing things like creating the default CephBlockPool and RBD StorageClass (among other things). As such, That's the CR that would have the information on what StorageClass will exist, and not the StorageCluster CR. So, we need to be creating the NooBaaSystem there.... unfortunately, that "there" doesn't exist yet. Thus, I'm putting a hold on this PR until we get that initialization CRD created. I'll try and get that moving this week.

/hold

**Comment by mhrivnak** [comment]
> Okay, so I've acquiesced to the current proposed design of having one NooBaaSystem per StorageCluster. However, I still believe this PR is incorrect. The reason is because we are also implementing a StorageClassInitialization CRD that will take care of doing things like creating the default CephBlockPool and RBD StorageClass (among other things). As such, That's the CR that would have the information on what StorageClass will exist, and not the StorageCluster CR. So, we need to be creating the NooBaaSystem there.... unfortunately, that "there" doesn't exist yet. Thus, I'm putting a hold on this PR until we get that initialization CRD created. I'll try and get that moving this week.

Since we're getting closer to a clear picture, it would help to write down what StorageClasses are going to get created and when. That would certainly help answer some of my questions about how things relate to each other and how hard we need to try to do things in a specific order.

With as much detail as you provide:
* What StorageClasses get created when the operator initializes?
* What StorageClasses get created when reconciling a StorageCluster cr? What information from the StorageCluster `Spec` will be used to create those StorageClasses?

**Comment by jarrpa** [comment]
> Since we're getting closer to a clear picture, it would help to write down what StorageClasses are going to get created and when. That would certainly help answer some of my questions about how things relate to each other and how hard we need to try to do things in a specific order.

Let's move this conversation out of this PR.

I've created #29 to implement the StorageClusterInitialization CRD, which is what should be doing the NooBaa initializations as well. I'll update this PR again when that merges.

**Comment by jarrpa** [comment]
#29 has merged, work on this can now resume.

/hold cancel

**Comment by obnoxxx** [comment]
@dannyzaken this needs rebase / update after some changes in master.

**Comment by obnoxxx** [comment]
@dannyzaken @guymguym ping

**Comment by dannyzaken** [comment]
@obnoxxx there are too many conflicts to update this PR. I will make a new PR and reference this PR from it.
I am still testing, should have the new PR later today

**Comment by obnoxxx** [comment]
@dannyzaken :
> @obnoxxx there are too many conflicts to update this PR. I will make a new PR and reference this PR from it.

You can also just locally rebase/rework and force-push over this one. But if you want to create a new PR, that would work too.

> I am still testing, should have the new PR later today

OK, thanks!

**Comment by dannyzaken** [comment]
@obnoxxx thanks. I already implemented on a different branch so I'll just create a new PR

**Comment by dannyzaken** [comment]
created PR #77 to replace this PR. closing

**Pull request closed without merging**
