### PR TITLE
csv: Update rook-ceph image

### PR DESCRIPTION
**Pull request by kshlm**
Rook Ceph image is updated to rook/ceph:v1.0.0-586.g8abcf37.dirty,
which fixes the cephcsi breakage.

This also adds documentation on the node taints and labels required.

See #71.

### CODE REVIEW

**Comment by kshlm** [comment]
/hold

until I verify.

**Comment by kshlm** [comment]
Even with the added taints and labels, we don't get a running cluster. Rook is currently failing to schedule the mgr pod. I'll be opening an issue on rook for this.

@jarrpa It's upto you if you'd like to merge this or not. Either way the latest OCS deployment is broken.

**Comment by obnoxxx** [comment]
@kshlm @jarrpa i think we might want to merge nonetheless because it gets us a step further. but leaving it up to you

**Comment by kshlm** [comment]
Opened rook/rook#3740 for this.

**Comment by kshlm** [comment]
@jarrpa If you do merge, please push updated ocs-registry images. And also, if you could, reply to my mail to rhocs-eng (subj: FYI, OCS operator upstream deployment currently broken)

**Comment by jarrpa** [comment]
It seems that running `make gen-latest-csv` generates some changes to the go.mod file that need to be committed. Also, rebase required.

**Pull request merged**
