### PR TITLE
predicates: avoid theoretical nil pointer deref

### PR DESCRIPTION
**Pull request by obnoxxx**
Signed-off-by: Michael Adam <obnox@redhat.com>

### CODE REVIEW

**Comment by obnoxxx** [comment]
@synarete - since we talked about it earlier today, FYI

**Review by raghavendra-talur — APPROVED** [review]

**Review by jarrpa — APPROVED** [review]
/lgtm

**Comment by jarrpa** [comment]
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ocs-operator/1156/pull-ci-openshift-ocs-operator-master-ocs-operator-bundle-e2e-aws/1384420533352796160/artifacts/ocs-operator-bundle-e2e-aws/ocs-must-gather/artifacts/ocs-must-gather/registry-build02-ci-openshift-org-ci-op-2812dhrd-stable-sha256-8604243ab3ef022b70d6f14a1dd8149430794e5eb8ca5d9f3eac3d3e5af462e0/namespaces/openshift-storage/pods/ocs-operator-7cfb648dd7-bqx8k/ocs-operator/ocs-operator/logs/current.log

**Pull request merged**
