### PR TITLE
Add test TestReconcileUninstallAnnotations

### PR DESCRIPTION
**Pull request by iamniting**

### CODE REVIEW

**Comment by iamniting** [comment]
@raghavendra-talur pls review last commit

**Comment by iamniting** [comment]
Screenshot from 2020-09-14 16-25-53

@raghavendra-talur All scenarios are covered except update error for this func

**Review by raghavendra-talur — APPROVED** [review]
Good test coverage! Thanks @iamniting

**Review by raghavendra-talur — APPROVED** [review]

**Review by obnoxxx — APPROVED** [review]
/lgtm

**Pull request merged**
