### PR TITLE
Bug 1770941: Bump noobaa-operator to 2.0.8

### PR DESCRIPTION
**Pull request by nimrod-becker**
Bump noobaa-operator to 2.0.8

### CODE REVIEW

**Comment by nimrod-becker** [comment]
Bug is already in verified, piggy-backing on another one

**Comment by jarrpa** [comment]
Holding to cut down spam.

/hold

**Comment by obnoxxx** [comment]
/lgtm cancel

because of @kshlm's request

**Comment by obnoxxx** [comment]
/test ocs-operator-ci

not sure. we didn't get results from that one...

**Comment by obnoxxx** [comment]
/hold cancel

everything good now

**Pull request merged**
