### PR TITLE
Bug 1979263: [release-4.8] revert: creation of thick provisioned storage class in 4.8

### PR DESCRIPTION
**Pull request by agarwal-mudit**
Thick provisioning feature is now dev preview, hence removing
the sc creation.

Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>

### CODE REVIEW

**Comment by agarwal-mudit** [comment]
/retitle Bug 1979263: [release-4.8] revert: creation of thick provisioned storage class in 4.8

**Comment by aruniiird** [comment]
Hi @agarwal-mudit , the changes look good...
Just for my clarification, you mentioned that 3 commits are reverted, but the whole Thick provision SC creation/implementation itself is removed. Do we really need to remove the implementation part, can we not just use the `false` parameter and not create Thick Provision SC?

**Comment by agarwal-mudit** [comment]
> Hi @agarwal-mudit , the changes look good...
> Just for my clarification, you mentioned that 3 commits are reverted, but the whole Thick provision SC creation/implementation itself is removed. Do we really need to remove the implementation part, can we not just use the `false` parameter and not create Thick Provision SC?

Good idea, but I am not sure if that will create two instances for thin provisioned SC?
I will wait for @jarrpa also to comment, we can do whatever looks good to everyone.

**Comment by agarwal-mudit** [comment]
Let me explain the commits here for the ease of review:

- One go fmt commit, just to satisfy golang-ci
- Two commits related to external storage are straight forward as the PRs for these had only these commits.
- PR for the third commit (https://github.com/openshift/ocs-operator/pull/1140/commits) has 4 commits:
    1. CSV changes for ManageCephDashboard  - **Not included in this PR**
    2. CSV changes for metricsExporter -> monitoring  - **Not included in this PR**
    3. refactor SC unit test to loop over SCs - **Not reverted just fixed the expected number of sc**
    4. Create RBD StorageClass with thick provisioning  - **Reverted without any issues.**

Didn't face any merge conflict while taking the reverts.

**Review by jarrpa — APPROVED** [review]
/lgtm

**Pull request merged**
