### PR TITLE
storagecluster: Enhance Noobaa ensureDeleted logging

### PR DESCRIPTION
**Pull request by iamniting**
Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1915737

cc @raghavendra-talur

### CODE REVIEW

**Review by raghavendra-talur — APPROVED** [review]

**Review by crombus — CHANGES_REQUESTED** [review]
Code changes looks good. I have request in commit description . can you add that what enhances the looging descriptively .

**Comment by iamniting** [comment]
> Code changes looks good. I have request in commit description . can you add that what enhances the looging descriptively .

Done

**Review by crombus — APPROVED** [review]

**Comment by raghavendra-talur** [comment]
@jarrpa @umangachapagain It would be good to have this PR merged for better debugging of uninstall. Please review.

**Review by jarrpa — APPROVED** [review]
/lgtm

**Pull request merged**
