### PR TITLE
Bug 1881071:Made monitoring optional during external cluster initilization

### PR DESCRIPTION
**Pull request by anmolsachan**
This PR is required to enable upgrades in external mode from 4.5 to 4.6 without any failure due to the requirement of monitoring info.

Signed-off-by: Anmol Sachan <anmol13694@gmail.com>

### CODE REVIEW

**Comment by obnoxxx** [comment]
@anmolsachan - why is the PR titled with [release-4.6] but it is against the master branch?

a PR against the release-4.6 branch would be expected to carry the `Bug 1234: ` and (optionally, for clarity) the `[release-4.6]` part in the title line.

**Comment by anmolsachan** [comment]
> @anmolsachan - why is the PR titled with [release-4.6] but it is against the master branch?
> 
> a PR against the release-4.6 branch would be expected to carry the `Bug 1234: ` and (optionally, for clarity) the `[release-4.6]` part in the title line.

@obnoxxx This needs to be merged to master and backported to 4.6. I have updated the title. Please review.

**Comment by anmolsachan** [comment]
@aruniiird @umangachapagain @jarrpa Please review.

**Review by jarrpa — APPROVED** [review]

**Pull request merged**
