### PR TITLE
Adding noobaa's core and db images to a new environment variables for the noobaa operator

### PR DESCRIPTION
**Pull request by jackyalbo**
In order to fix issue #372
Moving the responsibility to setup the noobaa images (core and db from the reconciler using the spec to a new environment variables used by the operator (https://github.com/noobaa/noobaa-operator/pull/194)
also fixed the corresponding test scenarios

### CODE REVIEW

**Comment by nimrod-becker** [comment]
@jarrpa ping

**Comment by nimrod-becker** [comment]
Do we have a problem with the CI ?

**Comment by jarrpa** [comment]
Currently checking with the openshift CI team.

**Comment by jarrpa** [comment]
https://github.com/openshift/ocs-operator/pull/392 merged just fine earlier today, so I'll try it one more time.

/test ocs-operator-e2e-aws

**Comment by jarrpa** [comment]
@jackyalbo something might be wrong with the PR itself. Can you spin up an OCP cluster and run the functional tests against it so we can try and figure out the problem?

**Comment by jackyalbo** [comment]
@jarrpa I deployed from my branch on top of CRC and it seems to be working - didn't create any storage cluster though as it running local on my mac.

**Comment by jarrpa** [comment]
We need to run the functional tests to find out what's going on, as there appears to be no broader CI problem. I can try to do it, but probably not before next week. If you don't already have an openshift-dev AWS account, you might consider doing so.

**Comment by obnoxxx** [comment]
again a csv generation needed

**Comment by guymguym** [comment]
bump @jackyalbo

**Comment by guymguym** [comment]
@obnoxxx @jarrpa We need this backported to 4.3.
Is there a plan to make a mass backport soon?

**Pull request merged**
