### PR TITLE
Bug 1846085: [release-4.5] Updates don't work on StorageClass

### PR DESCRIPTION
**Pull request by rajatsingh25aug**
Backport PR for commit [6e22082](https://github.com/openshift/ocs-operator/pull/590/commits/6e22082cff3cf7b364f9653191c0fb4794d5e5c6)

Backport of PR #590 

Signed-off-by: RAJAT SINGH <rajasing@redhat.com>

### CODE REVIEW

**Comment by rajatsingh25aug** [comment]
@umangachapagain Should I push one more time with a new `latest-csv-checksum`?. The command `verify-latest-csv` is passing on my machine locally.

**Comment by umangachapagain** [comment]
> @umangachapagain Should I push one more time with a new `latest-csv-checksum`?. The command `verify-latest-csv` is passing on my machine locally.

Push the update. CI needs to pass too.

**Comment by rajatsingh25aug** [comment]
> > @umangachapagain Should I push one more time with a new `latest-csv-checksum`?. The command `verify-latest-csv` is passing on my machine locally.
> 
> Push the update. CI needs to pass too.

Done already 👍

**Pull request merged**
