### PR TITLE
Properly set topologyKey in mon Placement

### PR DESCRIPTION
**Pull request by jarrpa**
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Review by obnoxxx — CHANGES_REQUESTED** [review]
please cover this code path with a unit test to prevent us from future regressions. looks good otherwise

**Comment by jarrpa** [comment]
Unit test(s) added.

**Review by obnoxxx — APPROVED** [review]
/lgtm

**Pull request merged**
