### PR TITLE
Make must-gather more efficient 

### PR DESCRIPTION
**Pull request by crombus**
problem: wait for different pods caused must-gather to execute by taking lot of time.

solution: for every pod must-gather creates should for only 5 minutes and debug pod can be used accros must-gather scripts.

### CODE REVIEW

**Review by rajatsing — APPROVED** [review]
LGTM

**Review by jarrpa — APPROVED** [review]
/lgtm

**Comment by jarrpa** [comment]
Looks good, please rebase.

**Review by jarrpa — APPROVED** [review]
/lgtm

**Pull request merged**
