### PR TITLE
Updated OCS telemeter rule name to match with OCP pattern

### PR DESCRIPTION
**Pull request by anmolsachan**
Signed-off-by: Anmol Sachan <anmol13694@gmail.com>

This is done to follow the convention OCP team follows as all the customers can see names of these rules.

### CODE REVIEW

**Comment by umangachapagain** [comment]
Is there any specific need to do this or is it just a cosmetic change?

**Comment by anmolsachan** [comment]
> Is there any specific need to do this or is it just a cosmetic change?

This is a cosmetic change, but it's good to follow convention.

**Pull request merged**
