### PR TITLE
storagecluster: Fix intermediate ready phase in storage cluster during installation

### PR DESCRIPTION
**Pull request by kesavanvt**
Signed-off-by: kesavan <kvellalo@redhat.com>

### CODE REVIEW

**Comment by kesavanvt** [comment]
@jarrpa PTAL

**Review by umangachapagain — COMMENTED** [review]
@kesavanvt Commit looks fine, but title says "intermediate ready phase".
Are you trying to fix phase (which is `status.phase`) or conditions (which is `status.conditions`)?

**Comment by kesavanvt** [comment]
> @kesavanvt Commit looks fine, but title says "intermediate ready phase".
> Are you trying to fix phase (which is `status.phase`) or conditions (which is `status.conditions`)?

The `status.phase` will be fixed by the addition of above condition. As the `status.phase` gets to `Ready` only when there is no conditions reported by the components.

**Comment by umangachapagain** [comment]
> > @kesavanvt Commit looks fine, but title says "intermediate ready phase".
> > Are you trying to fix phase (which is `status.phase`) or conditions (which is `status.conditions`)?
> 
> The `status.phase` will be fixed by the addition of above condition. As the `status.phase` gets to `Ready` only when there is no conditions reported by the components.

Let's add this explanation to the commit message.

**Comment by kesavanvt** [comment]
> > > @kesavanvt Commit looks fine, but title says "intermediate ready phase".
> > > Are you trying to fix phase (which is `status.phase`) or conditions (which is `status.conditions`)?
> > 
> > 
> > The `status.phase` will be fixed by the addition of above condition. As the `status.phase` gets to `Ready` only when there is no conditions reported by the components.
> 
> Let's add this explanation to the commit message.

Done

**Review by umangachapagain — APPROVED** [review]
/lgtm

**Pull request merged**
