### PR TITLE
[release-4.8]Bug 1979012: Disable thick provisioning support from UI

### PR DESCRIPTION
**Pull request by bipuladh**
- Change feature guard annotations in CSV to diable thick provisioning from UI

Partial revert of: #1142

/assign @umangachapagain

### CODE REVIEW

**Review by umangachapagain — APPROVED** [review]

**Comment by agarwal-mudit** [comment]
Can we keep these changes only in release-4.8?
I have done the same in https://github.com/openshift/ocs-operator/pull/1257

I have already checked the same with Eran, we don't want to disable this for 4.9 as of now.

**Review by agarwal-mudit — APPROVED** [review]
/lgtm

**Pull request merged**
