### PR TITLE
ceph: add retry to acquire flock

### PR DESCRIPTION
**Pull request by agarwal-mudit**
Adding "bdev_flock_retry = 20" to the [global] section
of the defaultRookConfigData var.

Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>

### CODE REVIEW

**Comment by agarwal-mudit** [comment]
@leseb I think bdev_flock_retry determines the number of retries and not the timespan,
bdev_flock_retry_interval is for the timespan.
https://github.com/ceph/ceph/blob/3e2c8e94fb9fb8421a08ca425b14833a981565a6/src/blk/kernel/KernelDevice.cc#L117

**Comment by leseb** [comment]
> @leseb I think bdev_flock_retry determines the number of retries and not the timespan,
> bdev_flock_retry_interval is for the timespan.
> https://github.com/ceph/ceph/blob/3e2c8e94fb9fb8421a08ca425b14833a981565a6/src/blk/kernel/KernelDevice.cc#L117

So what? We just want to retry not change the time between retries. I'm not sure I understand the concern.

**Comment by agarwal-mudit** [comment]
> > @leseb I think bdev_flock_retry determines the number of retries and not the timespan,
> > bdev_flock_retry_interval is for the timespan.
> > https://github.com/ceph/ceph/blob/3e2c8e94fb9fb8421a08ca425b14833a981565a6/src/blk/kernel/KernelDevice.cc#L117
> 
> So what? We just want to retry not change the time between retries. I'm not sure I understand the concern.

Not a concern, just wanted to clarify.

**Comment by agarwal-mudit** [comment]
@obnoxxx Please take a look.

**Review by obnoxxx — APPROVED** [review]
/lgtm

**Pull request merged**
