### PR TITLE
[DO NOT MERGE] WIP - testing replica 3 on 2 AZs. 

### PR DESCRIPTION
**Pull request by davidvossel**
Rook is working on fixing the issues we hit with running replica 3 on 2 AZs in our prow e2e test environment.

The easiest way to test this is to just run the prow e2e test in a PR using a custom rook image, which is what this PR aims to do.

### CODE REVIEW

**Comment by davidvossel** [comment]
2 successful e2e runs with Replica 3 using that new rook container image with the latest LVM fixes :)

**Comment by jarrpa** [comment]
Excellent! Do we want to consider this PR for merging once Rook publishes a new image?

**Comment by davidvossel** [comment]
> Excellent! Do we want to consider this PR for merging once Rook publishes a new image?

yeah, We can transform this into a mergable PR once the new ROOK image is published. All we would need to do is regenerate the CSV with the updated ROOK image and the rest should be good to go.

**Comment by davidvossel** [comment]
This is obsoleted by #148

**Pull request closed without merging**
