### PR TITLE
added DBType=postgres to noobaa CR

### PR DESCRIPTION
**Pull request by dannyzaken**
Signed-off-by: Danny Zaken <dannyzaken@gmail.com>

fix for https://bugzilla.redhat.com/show_bug.cgi?id=1922113

### CODE REVIEW

**Review by jarrpa — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by dannyzaken** [comment]
@jarrpa @umangachapagain any idea why the tests are failing? I see the same failures in other PRs

**Comment by jarrpa** [comment]
Not sure why the e2e tests are failing, but it may be legit. Unfortunately I can't seem to find any OCS must-gather files, which may be another problem entirely. Can you reproduce this on your own AWS cluster, or at least verify that the e2e tests pass?

**Comment by jarrpa** [comment]
@dannyzaken Tests are still failing. Can you do any testing yourself to confirm that this works in a cluster outside the CI?

**Comment by dannyzaken** [comment]
@jarrpa I am trying to get a cluster to test on. turns out it's not an easy task. will notify once verified

**Comment by dannyzaken** [comment]
I tried to install on two clusters, AWS and GCP. In ocs logs I see these messages repeating:
```
"level":"info","ts":1613052423.1318004,"logger":"controllers.OCSInitialization","msg":"Reconciling OCSInitialization","Request.Namespace":"openshift-storage","Request.Name":"ocsinit"}
{"level":"error","ts":1613052423.1340735,"logger":"controllers.OCSInitialization","msg":"Failed to add conditions to status","Request.Namespace":"openshift-storage","Request.Name":"ocsinit","error":"ocsinitializations.ocs.openshift.io \"ocsinit\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/dannyzaken/code/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\ngithub.com/openshift/ocs-operator/controllers/ocsinitialization.(*OCSInitializationReconciler).Reconcile\n\t/Users/dannyzaken/code/go/src/github.com/openshift/ocs-operator/controllers/ocsinitialization/ocsinitialization_controller.go:249\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/dannyzaken/code/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:244\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/dannyzaken/code/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/Users/dannyzaken/code/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/Users/dannyzaken/code/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/Users/dannyzaken/code/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/Users/dannyzaken/code/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/Users/dannyzaken/code/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90"}
{"level":"error","ts":1613052423.1341543,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"ocs.openshift.io","reconcilerKind":"OCSInitialization","controller":"ocsinitialization","name":"ocsinit","namespace":"openshift-storage","error":"ocsinitializations.ocs.openshift.io \"ocsinit\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/dannyzaken/code/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/dannyzaken/code/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:246\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/dannyzaken/code/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/Users/dannyzaken/code/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/Users/dannyzaken/code/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/Users/dannyzaken/code/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/Users/dannyzaken/code/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/Users/dannyzaken/code/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90"}
```

any idea what can be the cause? doesn't look connected to my changes, but can it be related somehow?

**Comment by dannyzaken** [comment]
in the ocs logs [here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ocs-operator/1023/pull-ci-openshift-ocs-operator-master-ocs-operator-bundle-e2e-aws/1359791493685972992/artifacts/ocs-operator-bundle-e2e-aws/gather-extra/artifacts/pods/openshift-storage_ocs-operator-7cb9887b9f-42qtv_ocs-operator.log) I see different messages:

```
{"level":"info","ts":1613039981.04606,"logger":"controllers.StorageCluster","msg":"Creating CephCluster","Request.Namespace":"openshift-storage","Request.Name":"test-storagecluster"}
{"level":"info","ts":1613039981.0628586,"logger":"controllers.StorageCluster","msg":"Waiting on ceph cluster to initialize before starting noobaa","Request.Namespace":"openshift-storage","Request.Name":"test-storagecluster"}
E0211 10:39:41.325809       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to watch *v1.CustomResourceDefinition: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:openshift-storage:ocs-operator" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
E0211 10:39:42.254643       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to watch *v1.CustomResourceDefinition: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:openshift-storage:ocs-operator" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
E0211 10:39:44.828279       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to watch *v1.CustomResourceDefinition: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:openshift-storage:ocs-operator" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
E0211 10:39:51.151303       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to watch *v1.CustomResourceDefinition: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:openshift-storage:ocs-operator" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

**Comment by dannyzaken** [comment]
@jarrpa @umangachapagain @obnoxxx any ideas?

**Comment by jarrpa** [comment]
Bug introduced that's being fixed here: https://github.com/openshift/ocs-operator/pull/1059

**Comment by dannyzaken** [comment]
@jarrpa the tests seem to pass now

**Comment by dannyzaken** [comment]
@jarrpa @obnoxxx rebased the PR, waiting to merge once the tests pass

**Pull request merged**
