### PR TITLE
Fixed incorrect logr usage

### PR DESCRIPTION
**Pull request by nbalacha**
The logr implementation encourages structured logging.

Fixes issue: #757 

Signed-off-by: N Balachandran <nibalach@redhat.com>

### CODE REVIEW

**Comment by nbalacha** [comment]
There are 2 ways I see to fix this, both of which have been added to the code. Once we decide on the approach, I will remove the second one.

Old:
`	r.reqLogger.Info("reconciling metrics exporter service %v", namespacedName)

Output:
{"level":"dpanic","ts":"2020-09-08T14:45:48.477Z","logger":"controller_storagecluster","msg":"odd number of arguments passed as key-value pairs for logging","ignored key":{"namespace":"openshift-storage","name":"ocs-metrics-exporter"},"stacktrace":"github.com/go-logr/zapr.handleFields\n\t/home/nibalach/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:106\ngithub.com/go-logr/zapr.(*infoLogger).Info\n\t/home/nibalach/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:70\ngithub.com/openshift/ocs-operator/pkg/controller/storagecluster.CreateOrUpdateService\n\t/home/nibalach/go/src/github.com/ocs-operator/ocs-operator/pkg/controller/storagecluster/exporter.go:93\ngithub.com/openshift/ocs-operator/pkg/controller/storagecluster.(*ReconcileStorageCluster).enableMetricsExporter\n\t/home/nibalach/go/src/github.com/ocs-operator/ocs-operator/pkg/controller/storagecluster/exporter.go:32\ngithub.com/openshift/ocs-operator/pkg/controller/storagecluster.(*ReconcileStorageCluster).Reconcile\n\t/home/nibalach/go/src/github.com/ocs-operator/ocs-operator/pkg/controller/storagecluster/reconcile.go:350\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/nibalach/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/nibalach/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/nibalach/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/nibalach/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/nibalach/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/nibalach/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88"}
{"level":"info","ts":"2020-09-08T14:45:48.477Z","logger":"controller_storagecluster","msg":"reconciling metrics exporter service %v"}

`

	
Approach 1:
`       reqLogger := r.reqLogger.WithValues("Service.Namespace", service.Namespace, "Service.Name", service.Name)
	reqLogger.Info("Reconciling metrics exporter service")

Output:
{"level":"info","ts":"2020-09-09T07:29:35.886Z","logger":"controller_storagecluster","msg":"Reconciling metrics exporter service","Service.Namespace":"openshift-storage","Service.Name":"ocs-metrics-exporter"}`


Approach 2:
`	r.reqLogger.Info("Reconciling metrics exporter service", "NamespacedName", namespacedName)

Output:
{"level":"info","ts":"2020-09-09T07:29:35.886Z","logger":"controller_storagecluster","msg":"Reconciling metrics exporter service","NamespacedName":{"namespace":"openshift-storage","name":"ocs-metrics-exporter"}}`

**Comment by umangachapagain** [comment]
Hey thanks for the fix. I keep forgetting the usage and make the same mistake repeatedly :facepalm:
It'd be great if we could catch this during build or lint tests. 

Let's go with approach 2.

**Review by obnoxxx — CHANGES_REQUESTED** [review]
@nbalacha thanks for the patch!

If I understand the commits correctly, the first commit implements both approaches (1 and 2) explained in the comments, and the two follow-up commits remove approach 1.

So if you squash the three commits together into one, we can merge it.

**Comment by nbalacha** [comment]
> @nbalacha thanks for the patch!
> 
> If I understand the commits correctly, the first commit implements both approaches (1 and 2) explained in the comments, and the two follow-up commits remove approach 1.
> 
> So if you squash the three commits together into one, we can merge it.

Done. Thanks @obnoxxx

**Review by obnoxxx — APPROVED** [review]
code change looks good to me now.

/lgtm

you lost your signoff tag in the commit message, you can still add if but won't block the pr for it

**Comment by umangachapagain** [comment]
@nbalacha Automatic cherry-pick failed. Can you create a manual backport for release-4.6?

**Comment by nbalacha** [comment]
Will do.

**Comment by nbalacha** [comment]
> @nbalacha Automatic cherry-pick failed. Can you create a manual backport for release-4.6?

@umangachapagain , Looks like this does not need to be backported to 4.6 - these logr calls do not exist in that branch.

**Comment by raghavendra-talur** [comment]
We do have logr calls in the release 4.6 branch now. I will try to cherrypick this one again.

**Pull request merged**
