### PR TITLE
Added Deleting Phase to the Storage Cluster

### PR DESCRIPTION
**Pull request by nizamial09**
Added a phase called Deleting which will show when the cluster is getting deleted.

Screenshot from 2020-02-07 15-05-56

Signed-off-by: Nizamudeen <nia@redhat.com>

### CODE REVIEW

**Comment by jarrpa** [comment]
Don't worry about the ocs-ci test. It's currently broken and we don't require it anyway.

**Comment by nizamial09** [comment]
> Don't worry about the ocs-ci test. It's currently broken and we don't require it anyway.

Oh good. I was getting prepared to comment  retest like firing from the machine gun.

**Comment by nizamial09** [comment]
> Don't worry about the ocs-ci test. It's currently broken and we don't require it anyway.

Oh good. I was getting prepared to comment  retest like firing from the machine gun.

**Pull request merged**
