### PR TITLE
Upgrade rook to v1.5.6 and K8s to v0.20.2

### PR DESCRIPTION
**Pull request by aruniiird**
Upgrading rook version to 1.5.6.
This includes kubernetes dependencies updation as well.

### CODE REVIEW

**Comment by aruniiird** [comment]
@umangachapagain , @jarrpa , please take a look...

**Review by jarrpa — CHANGES_REQUESTED** [review]
It seems invalid that we are removing the Rook-Ceph CRD entries in the CSV. Is this expected?

/ok-to-test

**Comment by umangachapagain** [comment]
> It seems invalid that we are removing the Rook-Ceph CRD entries in the CSV. Is this expected?
> 
> /ok-to-test

Yes, it actually fixes an issue with duplicate entries in CSV.

**Review by umangachapagain — APPROVED** [review]

**Review by jarrpa — APPROVED** [review]
/lgtm

**Review by jarrpa — APPROVED** [review]
/lgtm

**Pull request merged**
