### PR TITLE
Bug 1768874: Disable CephObjectStore when the cloud provider is AWS.

### PR DESCRIPTION
**Pull request by rohantmp**
When the cloud provider is AWS, AWS S3 will provide object storage instead of RGW.

Signed-off-by: Rohan CJ <rohantmp@redhat.com>

### CODE REVIEW

**Comment by rohantmp** [comment]
This is a backport for #318

**Comment by obnoxxx** [comment]
updated the PR to include the last update to #318 (`!=` instead of `==` in tests...)

**Comment by obnoxxx** [comment]
updated with further test fixes from #318

**Pull request merged**
