### PR TITLE
Remove dependency to local-storage-operator

### PR DESCRIPTION
**Pull request by umangachapagain**
Updates CSV v0.0.1 and v0.0.2 to remove the dependency to local-storage-operator.

### CODE REVIEW

**Comment by obnoxxx** [comment]
There's possibly one additional thing needed

**Comment by sacharya** [comment]
@umangachapagain Could you also remove all unused references of localStorageRegistryImage? See tools/cluster-deploy and pkg/deploy-manager.

**Comment by obnoxxx** [comment]
@sacharya writes:
> @umangachapagain Could you also remove all unused references of localStorageRegistryImage? See tools/cluster-deploy and pkg/deploy-manager.

Please do this in a separate follow-up PR, as discussed offline.

/lgtm

**Comment by sacharya** [comment]
#317 is the followup PR.

**Comment by kshlm** [comment]
/hold

Till we figure out the problem with the e2e tests.

**Comment by obnoxxx** [comment]
@umangachapagain  i just ameneded your commit message without changing anything to trigger full new image build in the ci. Hope this will get us unstuck...

**Comment by obnoxxx** [comment]
FWIW, since the introduction of the version 0.0.2 of the csv, we've only been updating that in the `master` branch (via `make gen-latest-csv`). That means for backport to `release-4.2`, it's not a clean cherry-pick if it touches the csv, but you need to run `make gen-latest-csv` for the 4.2 branch when backporting.

So I think the 0.0.1 commit of this PR could/should be omitted?!

**Comment by umangachapagain** [comment]
Removed the 0.0.1 commit.

**Comment by obnoxxx** [comment]
/test ocs-operator-e2e-aws

retest this since #321 merged...

**Pull request merged**
