### PR TITLE
Storagecluster: generate mgr spec in a function

### PR DESCRIPTION
**Pull request by raghavendra-talur**
This also updates the count of MGRs that are created for an arbiter
deployment to 2.

Signed-off-by: Raghavendra Talur <raghavendra.talur@gmail.com>

### CODE REVIEW

**Comment by raghavendra-talur** [comment]
We now have the version of Rook which has the MGR count member in the MGR spec.

cc: @travisn

**Comment by raghavendra-talur** [comment]
Need to work on the review comment provided in an older PR https://github.com/openshift/ocs-operator/pull/1151#discussion_r612947852

**Review by obnoxxx — APPROVED** [review]
looks good

**Review by jarrpa — COMMENTED** [review]
This looks fine, any reason it's still WIP?

**Comment by raghavendra-talur** [comment]
@obnoxxx @jarrpa I have updated the PR now. It was in WIP because I had not added the resources limits for the mgr sidecar container. It is added now.

**Comment by jarrpa** [comment]
Looks like you may have pushed the wrong commit. You're missing some curly braces and didn't clean up a merge conflict.

**Comment by raghavendra-talur** [comment]
> Looks like you may have pushed the wrong commit. You're missing some curly braces and didn't clean up a merge conflict.

Thank you. Updated now.

**Review by jarrpa — APPROVED** [review]
/lgtm

**Pull request merged**
