### PR TITLE
Default RBD storageclass to "ext4"

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by kshlm** [comment]
@humblec Is this a standalone change or do we also need an update to the rook image used for it to work?

**Comment by Madhu-1** [comment]
> @humblec Is this a standalone change or do we also need an update to the rook image used for it to work?

@kshlm we don't need any  rook or cephcsi changes as  this is a change in storage-class standard parameter

**Comment by humblec** [comment]
@kshlm as mentioned in previous comment, this can survive alone.  The rook changes which do more enhancements for "Ext4" will eventually pickup. So as far as we use latest rook, we are good !

**Comment by kshlm** [comment]
Thanks for the clarifications @humblec @Madhu-1 

/lgtm

**Pull request merged**
