### PR TITLE
Update rook csv rook/ceph:v1.5.0.737.g5478956

### PR DESCRIPTION
**Pull request by obnoxxx**
This is a spin-off of #1141 which aims at updating rook to the latest and greatest for both the csv and the go dependency. Because the go dependency implies more work around the codebase, this PR spins off just the csv part of the rook update.

### CODE REVIEW

**Review by jarrpa — APPROVED** [review]
/lgtm

**Comment by obnoxxx** [comment]
@jarrpa  - this fails the same way as #1141...

**Comment by obnoxxx** [comment]
superseded by #1150

**Pull request closed without merging**
