### PR TITLE
Update CSV to use taint-nodes

### PR DESCRIPTION
**Pull request by Jayashree-panda**
Signed-off-by: Jayashree-panda <jayashreepanda12345@gmail.com>
Adding taint-nodes to annotations will allow UI to apply taint on selected nodes for OCS cluster creation.

### CODE REVIEW

**Review by umangachapagain — COMMENTED** [review]
Split `.go` and `.yaml` changes into separate commits.
Briefly explain what it does.

**Review by umangachapagain — COMMENTED** [review]
```
Update CSV to use taint-nodes in yaml

Adding taint-nodes to annotations will allow UI to apply taint on
selected nodes for OCS cluster creation

Signed-off-by: Jayashree-panda <jayashreepanda12345@gmail.com>
```

This is how you should format commit message (See [Contributing Guide](https://github.com/openshift/ocs-operator/blob/master/CONTRIBUTING.md#commit-and-pull-request-messages))

**Comment by jarrpa** [comment]
Also... just to be a stickler, the commits should be in reverse order. The change to the merger should come first, and then the generated changes should come afterwards.

**Comment by jarrpa** [comment]
Oh, and I just noticed: You should be using your @redhat.com email address in all your signatures.

**Comment by Jayashree-panda** [comment]
> Oh, and I just noticed: You should be using your @redhat.com email address in all your signatures.

My github account is linked with my personal email and not the @redhat.com.

**Review by jarrpa — APPROVED** [review]
/lgtm

**Pull request merged**
