### PR TITLE
adds OCSInitialData resource

### PR DESCRIPTION
**Pull request by mhrivnak**
This resource represents the initial data that should be created when the
operator gets installed. Currently it includes two demo StorageClass resources,
which should be changed to match what OCS wants to install in production.

Deleting the OCSInitialData resource will cause it to be auto-recreated, and
then all initial data will be reset or recreated as necessary to restore their
initial state.

### CODE REVIEW

**Comment by mhrivnak** [comment]
> Thanks for the PR! Some overall comments:
> 
> * I don't like the name `OCSInitialData`, because this represents more than just static data being generated. I'd like to see it changed to something like `OCSInitialization` or `OCSOperatorInit`

Will do. I'll go for `OCSInitialization` unless anyone wants to express further opinion on it.

> * Does it matter if we use booleans as opposed to a Condition to track state?

Conditions would be a marginal improvement from a design and ecosystem perspective, but not necessarily more useful. This API is intended for internal use by the operator itself. The main reason to use conditions would be if we think the boolean could have more than two values. For example, maybe an "unknown" value would be useful. Maybe a "progressing" value would be useful.

In this case, I'd argue neither of those would be useful. I suggest trying it as a boolean, getting additional feedback, and then it would be straight-forward to convert to conditions prior to GA if that would be desirable.

> * Don't create any StorageClasses yet. Just leave an empty reconcile loop we can fill in later, maybe leave a `TODO` comment where we should start adding functions. For now just have some boolean/condition to track if the initialization is "Completed".

Will do. I'll just point out that the feature is impossible to test unless some data gets created. Do you intend to add "real" storage classes to this soon?

To the details of your comment, the reconcile function can't really be empty; it's a large part of the work related to implementing this behavior. The `newStorageClasses` function is where, you guessed it, new storage classes should be defined. It even already has a TODO comment to add the real ones. I'll remove the demo ones from that function, but leave the function and all other related logic in-place.

**Comment by mhrivnak** [comment]
@jarrpa done. Let me know if you'd like the changes squashed.

**Comment by jarrpa** [comment]
> > * Does it matter if we use booleans as opposed to a Condition to track state?
> 
> Conditions would be a marginal improvement from a design and ecosystem perspective, but not necessarily more useful. This API is intended for internal use by the operator itself. The main reason to use conditions would be if we think the boolean could have more than two values. For example, maybe an "unknown" value would be useful. Maybe a "progressing" value would be useful.
> 
> In this case, I'd argue neither of those would be useful. I suggest trying it as a boolean, getting additional feedback, and then it would be straight-forward to convert to conditions prior to GA if that would be desirable.

Good enough for me.

> > * Don't create any StorageClasses yet. Just leave an empty reconcile loop we can fill in later, maybe leave a `TODO` comment where we should start adding functions. For now just have some boolean/condition to track if the initialization is "Completed".
> 
> Will do. I'll just point out that the feature is impossible to test unless some data gets created. Do you intend to add "real" storage classes to this soon?

Yes. I don't have a need to immediately test this at this time.

> To the details of your comment, the reconcile function can't really be empty; it's a large part of the work related to implementing this behavior. The `newStorageClasses` function is where, you guessed it, new storage classes should be defined. It even already has a TODO comment to add the real ones. I'll remove the demo ones from that function, but leave the function and all other related logic in-place.

That's more what I wanted, anyway, so that works.

Looks good overall, please squash and I'll merge.

**Comment by mhrivnak** [comment]
Squash complete.

**Pull request merged**
