### PR TITLE
adding .Status.Phase to OCS Custom Resources for OLM UI integration

### PR DESCRIPTION
**Pull request by umangachapagain**
Having .Status.Phase spec allows OLM UI to report the overall state
to the user without having to dig in to the resource description.

Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>

### CODE REVIEW

**Comment by djzager** [comment]
> It was not enough. Only because OLM UI expects a .Status.Phase spec to report status of the system. This is the first level status which can guide user to dig deeper if needed.
> 
> Personally, I find already available information enough to diagnose the system, but there were a bunch of bugs/feature requests to make it easily available in the UI.

Some references -- links to OLM source, screenshots from OpenShift UI before and after, or OLM documentation -- would be extremely helpful.

> Having .Status.Phase spec allows OLM UI to report the overall state
> to the user without having to dig in to the resource description.

This doesn't surprise me really. Keep in mind that PRs are more than just the patch, they are also a historical record of what changes were made and why, so it would be helpful to me and others to have links to who specifically is looking at `.Status.Phase` as well as links to issues since UI components should be able to handle Conditions.

**Comment by djzager** [comment]
This is especially true @umangachapagain since I can't find any indication in OLM's project -- source code or otherwise -- to suggest they are looking at the .Status.Phase of CustomResources at all.

**Comment by umangachapagain** [comment]
> Some references -- links to OLM source, screenshots from OpenShift UI before and after, or OLM documentation -- would be extremely helpful.
>
Agreed, I should have provided more context. Here it is,
This is the UI code that looks for [.Status.Phase](https://github.com/openshift/console/blob/c0c6fc13b78efba63f7c2388e12738819d7a626c/frontend/public/components/operator-lifecycle-manager/operand.tsx#L90) and [.Spec.Version](https://github.com/openshift/console/blob/c0c6fc13b78efba63f7c2388e12738819d7a626c/frontend/public/components/operator-lifecycle-manager/operand.tsx#L93) to populate the Operand listing table.

Status Column in the image below is the outcome of this PR. Version Column is still blank as we did not implement Spec.Version.
Screenshot from 2019-09-18 11-28-49

Looking from the design perspective, displaying entire Conditions Object in a column wouldn't scale and UI should not handle parsing these items. We should do this at the back-end.

**Comment by djzager** [comment]
Thanks a ton. It is really helpful to see screenshot + relevant portions of the UI source. While we may want to consider raising an issue that they should be able to display conditions...as that's what is being encouraged by the [api-conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties), I agree with what you have done.

> Some resources in the v1 API contain fields called phase, and associated message, reason, and other status fields. The pattern of using phase is deprecated. Newer API types should use conditions instead. Phase was essentially a state-machine enumeration field, that contradicted system-design principles and hampered evolution, since adding new enum values breaks backward compatibility. Rather than encouraging clients to infer implicit properties from phases, we prefer to explicitly expose the individual conditions that clients need to monitor. Conditions also have the benefit that it is possible to create some conditions with uniform meaning across all resource types, while still exposing others that are unique to specific resource types. See #7856 for more details and discussion.

**Pull request merged**
