### PR TITLE
enhance: Adds code for OCS-must-gather

### PR DESCRIPTION
**Pull request by ashishranjan738**
This commit adds code for ocs-must-gather and also implements Makefile for building the ocs-operator and ocs-must-gather images.

Signed-off-by: Ashish Ranjan <aranjan@redhat.com>

### CODE REVIEW

**Comment by ashishranjan738** [comment]
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by: _[ashishranjan738](https://github.com/openshift/ocs-operator/pull/9#)_, _[dannyzaken](https://github.com/openshift/ocs-operator/pull/9#pullrequestreview-264524287)_
> To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jarrpa**
> You can assign the PR to them by writing `/assign @jarrpa` in a comment when ready.
> 
> The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=openshift%2Focs-operator).
> 
> Needs approval from an approver in each of these files:
> * **[OWNERS](https://github.com/openshift/ocs-operator/blob/master/OWNERS)**
> 
> Approvers can indicate their approval by writing `/approve` in a comment
> Approvers can cancel approval by writing `/approve cancel` in a comment

done @jarrpa

**Comment by ashishranjan738** [comment]
> Thanks for this PR! A few things:
> 
> * Rename `ocs-must-gather` directory to just `must-gather`
> * Move the new `OWNERS` file one level higher
> * Create an initial Makefile as a separate commit, then add the must-gather target in a separate commit

done @jarrpa

**Comment by jarrpa** [comment]
Having a commit with an empty Makefile is pointless. You should split the current Makefile over two commits, one with most of the Makefile and then another one that adds the must-gather-specific target. The latter work can be part of the main commit that adds all the must-gather files, too.

**Comment by ashishranjan738** [comment]
> Having a commit with an empty Makefile is pointless. You should split the current Makefile over two commits, one with most of the Makefile and then another one that adds the must-gather-specific target. The latter work can be part of the main commit that adds all the must-gather files, too.

cool done @jarrpa

**Pull request merged**
