### PR TITLE
must-gather: add logs in debug file that were skipped

### PR DESCRIPTION
**Pull request by rajatsing**
added echo messages in the gather debug log file.

Signed-off-by: RAJAT SINGH <rajasing@redhat.com>

### CODE REVIEW

**Review by crombus — CHANGES_REQUESTED** [review]
This is bug which I feel we can find in other scripts as well. Look if there are another lines which we are not adding gather-debug.log.  Fix all the lines in this PR.

**Review by jarrpa — APPROVED** [review]
/lgtm

**Comment by jarrpa** [comment]
Oops, didn't notice Pulkit's review. Ignore me!

**Review by crombus — APPROVED** [review]
/lgmt

**Review by crombus — CHANGES_REQUESTED** [review]
rajat use imperative commit msg.

**Comment by rajatsing** [comment]
ok, so CI is failing which is a bit strange!. Nothing's breaking from the code's perspective.

**Comment by rajatsing** [comment]
I have re-triggered the CI.

**Comment by umangachapagain** [comment]
@crombus Can we merge this now?

**Comment by crombus** [comment]
> @crombus Can we merge this now?

no,  the commit msg doesn’t have must-gather tag and still not imperative commit msg.

**Comment by rajatsing** [comment]
@umangachapagain @crombus please go ahead and merge!.

**Review by crombus — APPROVED** [review]
/lgtm

**Pull request merged**
