### PR TITLE
Bug 1888614: Changed the execution of connection closing, to avoid closing uncreated connection.

### PR DESCRIPTION
**Pull request by anmolsachan**
Signed-off-by: anmol sachan <anmol13694@gmail.com>

### CODE REVIEW

**Review by nbalacha — COMMENTED** [review]
IIUC, the issue here is that the con was not created because the endpoint was unreachable so trying to access con.Close() it will fail. The defer statement is not the problem - it is the incorrect error handling in this case.

Can you update the commit message to add more detail on the cause?

**Comment by anmolsachan** [comment]
> IIUC, the issue here is that the con was not created because the endpoint was unreachable so trying to access con.Close() it will fail. The defer statement is not the problem - it is the incorrect error handling in this case.
> 
Yes, That is correct.
> Can you update the commit message to add more detail on the cause?
Sure.

**Comment by anmolsachan** [comment]
@nbalacha Done. Thanks for the review.

**Review by jarrpa — APPROVED** [review]

**Pull request merged**
