### PR TITLE
Bug 1764525: must-gather : error in syntax reported during ocs must-gather

### PR DESCRIPTION
**Pull request by ashishranjan738**
Signed-off-by: Ashish Ranjan <aranjan@redhat.com>

Backport of PR https://github.com/openshift/ocs-operator/pull/222

### CODE REVIEW

**Comment by guymguym** [comment]
Same as #222?

**Comment by ashishranjan738** [comment]
> Same as #222?

yeah backport of #222 for 4.2 branch.

**Comment by davidvossel** [comment]
I believe you'll need to reference a bz for this to get merged. look at the prow comment

**Pull request merged**
