### PR TITLE
update rook version from v1.1.1 to v1.1.2

### PR DESCRIPTION
**Pull request by Madhu-1**
some of the CSI bugs are fixed in rook v1.1.2 release and  we have added CSI toleration support in rook  v1.1.2 release

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

Fixes: #196

### CODE REVIEW

**Comment by Madhu-1** [comment]
/assign @jarrpa 
/assign @davidvossel 

let me know anything else  is required  apart from updating the rook version

**Comment by kshlm** [comment]
@Madhu-1 You also need to run `make gen-latest-csv` to update the CSV with the new image.

/ok-to-test

**Comment by Madhu-1** [comment]
@kshlm Thanks updated PR.

**Comment by kshlm** [comment]
Thanks.

/lgtm

**Pull request merged**
