### PR TITLE
Must-gather: Update OWNERS file

### PR DESCRIPTION
**Pull request by crombus**
Add rajatsing as reviwers and
remove ashishranjan738.

Signed-off-by: crombus <pkundra@redhat.com>

### CODE REVIEW

**Review by obnoxxx — COMMENTED** [review]
What's the purpose of only adding @rajatsing to the reviewers list but not approvers?

Acdording to the comments in the man OWNERS file  https://github.com/openshift/ocs-operator/blob/master/OWNERS#L1, "approvers" can add the "approved" label and "reviewers" can add the "lgtm" label. We usually add folks to both and don't make the distinction.

**Comment by obnoxxx** [comment]
@crombus  - What I was saying is that you may be misinterpreting the effect of putting someone into the "reviewers" list: If you put him in the reviewers list, then his "/lgtm" will be authoritative and will lead to get patches merged. At least that is my understanding.

And we usually add folks to both lists.

@jarrpa  to keep me honest

**Comment by jarrpa** [comment]
Michael is right, you want him under approvers not reviewers to prevent /LGTM access. But I think this is entirely unnecessary, you could just add him to both with the understanding he shouldn't LGTM anything just yet.

**Review by obnoxxx — CHANGES_REQUESTED** [review]
As @jarrpa confirmed, you should not only put him in reviewers, as it gives access to lgtm.
Either put him in approvers only, or put him in both.
I think both will be fine.

**Comment by crombus** [comment]
Understood and updated.

**Review by obnoxxx — APPROVED** [review]
/lgtm

**Pull request merged**
