### PR TITLE
Added annotation to the Job

### PR DESCRIPTION
**Pull request by xenolinux**
Added annotation template.alpha.openshift.io/wait-for-ready to the
object of a kind Job. This change ensures template readiness

Signed-off-by: Servesha Dudhgaonkar <sdudhgao@redhat.com>

### CODE REVIEW

**Comment by xenolinux** [comment]
Testing the changes locally....

**Comment by umangachapagain** [comment]
Can you add `Annotation template.alpha.openshift.io/wait-for-ready ensures template readiness` comment to the code also?

**Comment by xenolinux** [comment]
> Can you add `Annotation template.alpha.openshift.io/wait-for-ready ensures template readiness` comment to the code also?

@umangachapagain Sure, will do

**Pull request merged**
