### PR TITLE
Creating noobaa system in storageclusterinitialization_controller

### PR DESCRIPTION
**Pull request by dannyzaken**
creating a noobaa system when reconciling `StorageClusterInitializtion`

This is a follow PR to PR #13 (see discussion there)

### CODE REVIEW

**Comment by jarrpa** [comment]
Please split the vendor and go mod changes into their own commit.

**Comment by dannyzaken** [comment]
@jarrpa done

**Comment by obnoxxx** [comment]
@dannyzaken please rebase and force-push: part of the dep/vendor changes have been pushed in another PR in the meantime

**Comment by dannyzaken** [comment]
@obnoxxx done

**Comment by obnoxxx** [comment]
Thanks @dannyzaken 

/ok-to-test

**Comment by nimrod-becker** [comment]
Test failure
```
hack/source-manifests.sh: line 47: docker: command not found
make: *** [gen-latest-csv] Error 127
uncommitted CSV changes. run Generating latest development CSV version using predefined ENV VARs.
hack/generate-latest-csv.sh
=== Generating DEV CSV with the following vars ===
	CSV_VERSION=0.0.1
	ROOK_IMAGE=rook/ceph:v1.0.0-586.g8abcf37.dirty 
	NOOBAA_IMAGE=noobaa/noobaa-operator:1.1.0
	CEPH_IMAGE=ceph/ceph:v14.2.2-20190828
	OCS_IMAGE=quay.io/ocs-dev/ocs-operator:latest and commit results.
2019/09/03 12:14:49 Container test in pod verify-latest-csv failed, exit code 1, reason Error
```
Could we get some help as to what it means ?

**Comment by dannyzaken** [comment]
Does anyone know what's the problem with `verify-latest-csv`? 
it fails with `docker: command not found`, doesn't look related to my changes

**Comment by kshlm** [comment]
@dannyzaken @nimrod-becker The test itself needs some fixes. I have opened openshift/release#4913 to fix this. I'll have Jose merge it when he comes online soon.

**Comment by obnoxxx** [comment]
@kshlm strange, why didn't we have this in the recent PRs? Is that a flaky behavior?

**Comment by kshlm** [comment]
> @kshlm strange, why didn't we have this in the recent PRs? Is that a flaky behavior?

Yeah. Building `tools/csv-checksum` updates `go.sum` sometimes. This caused the check in the test to fail. I've fixed the test to only check the status of `hack/latest-csv-checksum.md5` and ignore other changes.

**Pull request merged**
