### PR TITLE
Bug 1849105: [release-4.5] StorageCluster: delete the default node selector labels during uninstall

### PR DESCRIPTION
**Pull request by raghavendra-talur**
This is a cherry-pick of #558 .

To be merged after

#575 and #574

### CODE REVIEW

**Comment by raghavendra-talur** [comment]
/assign raghavendra-talur
@jarrpa  @obnoxxx Please take a look.

**Comment by jarrpa** [comment]
Needs a rebase.

/hold cancel

**Comment by umangachapagain** [comment]
> Needs a rebase.
> 
> /hold cancel

BZs aren't approved. hence, I put it on hold.

**Comment by raghavendra-talur** [comment]
@jarrpa I rebased this one now. Will wait for it to merge before rebasing #557

**Pull request merged**
