### PR TITLE
Use .ci-operator.yaml file for OpenShift CI builds

### PR DESCRIPTION
**Pull request by BlaineEXE**
See docs:
https://docs.ci.openshift.org/docs/architecture/ci-operator/#build-root-image

Signed-off-by: Blaine Gardner <blaine.gardner@redhat.com>

### CODE REVIEW

**Review by jarrpa — APPROVED** [review]
/lgtm

**Comment by BlaineEXE** [comment]
Used with PR https://github.com/openshift/release/pull/21305

**Pull request merged**
