### PR TITLE
Bug 1913357: [release-4.7] Fail validation if arbiter and flexibleScaling both are enabled

### PR DESCRIPTION
**Pull request by agarwal-mudit**
Automated cherry-pick for https://github.com/openshift/ocs-operator/pull/1010 didn't work because of conflicts hence I am creating this request manually.

### CODE REVIEW

**Comment by agarwal-mudit** [comment]
@raghavendra-talur @jarrpa PTAL

**Review by jarrpa — APPROVED** [review]
/lgtm

**Comment by raghavendra-talur** [comment]
> @raghavendra-talur @jarrpa PTAL

Thanks for the backport @agarwal-mudit !

**Review by raghavendra-talur — APPROVED** [review]

**Pull request merged**
