### PR TITLE
Bug 1768874: Check for minimum number of storage nodes

### PR DESCRIPTION
**Pull request by jarrpa**
Backport #300. 

Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Comment by ashcrow** [comment]
Was this approved by the previous patch manager?

**Comment by obnoxxx** [comment]
@ashcrow wrote:
> Was this approved by the previous patch manager?

Sorry, what do you mean?

**Comment by obnoxxx** [comment]
what is a patch manager?

**Comment by eparis** [comment]
Sorry, we limit who/when people can commit to release-4.x branches. The query to see if anything slipped through found ocs-operator PRs. So Steve reached out. I'll fix the query to ignore ocs-oeprator.

**Comment by obnoxxx** [comment]
@eparis ok, sure. For the ocs-operator, the same people that can commit to master, can commit to release-4.2. It's a small group.

**Pull request merged**
