### PR TITLE
Bug 1798571: OB/OBC CRD not marked as Internal

### PR DESCRIPTION
**Pull request by umangachapagain**
Backport of #438

### CODE REVIEW

**Comment by obnoxxx** [comment]
@jarrpa , @umangachapagain  - what is this? BZ integration again? ... Should we merge manually?

**Comment by umangachapagain** [comment]
> @jarrpa , @umangachapagain - what is this? BZ integration again? ... Should we merge manually?

I put it on hold as backport of #424 is missing.

**Comment by sdodson** [comment]
> I put it on hold as backport of #424 is missing.
> Backport PR : #441

Are those independent fixes or should the two PRs be merged into one? We should not deliver an incomplete fix for a single bug.

**Comment by obnoxxx** [comment]
@sdodson 
These are not two parts of fixes for one bug. They are separate bugs.

**Comment by sdodson** [comment]
>  These are not two parts of fixes for one bug. They are separate bugs.

thanks, please clear the hold if you'd like this to go in

**Comment by obnoxxx** [comment]
@sdodson - I just learned that this PR is in fact depending on the other. It only makes sense on top of the other one... So the hold is valid at this poing as we're still debating #441. Sorry for the confusion!

**Comment by obnoxxx** [comment]
pr not going into 4.3. 
closing. 
will do again for 4.4

**Pull request closed without merging**
