### PR TITLE
Creating a new noobaa SCC

### PR DESCRIPTION
**Pull request by jackyalbo**
We want to create a noobaa own secure context in order to fix these two issues:
https://bugzilla.redhat.com/show_bug.cgi?id=1835125
https://bugzilla.redhat.com/show_bug.cgi?id=1804168

Currently trying to validate if this fix indeed resolves our upgrade issue

Signed-off-by: jackyalbo jalbo@redhat.com

### CODE REVIEW

**Comment by obnoxxx** [comment]
Sorry, I didn't mean to approve yet.
Running tests first. And hoping for more context in the commit msg.

**Comment by obnoxxx** [comment]
@jackyalbo - thanks for the udpate! Waiting for your verification results.

**Comment by jackyalbo** [comment]
After adding higher priority to the Nobbaa's SCC it is now works after both upgrade and after adding anyuid to system:authenticated

**Pull request merged**
